### ISSUE TITLE
Move to a better place

### ISSUE THREAD

**Issue by musicsd** [SeaDve/Kooha#1]
congratulations! This is a good program, GNOME needs such programs…

Unfortunately, I have to say that you have put this program in a bad place! GitHub!
This app deserves places like: GNOME's GitLab, Codeberg and wherever better…
GitHub boycotts users, removes apps, and actually says (whatever I want stays, and whatever I don't want is removed). The app has not paid attention to users' requests for RTL support for years, and says this is not a priority!
Free software should be free somewhere, which GitHub does not have!
Aren't these enough to leave GitHub?

**Comment by SeaDve** [comment]
Thanks! 

Yeah, I have been considering on moving to GitLab. However, I think I would first focus first on fixing bugs and improving the application. 

I will keep this issue open, so in the future, when I have time, I'll possibly move it to GNOME GitLab.

**Comment by TheOPtimal** [comment]
GNOME Gitlab would be an amazing place to move to.

**Comment by p00f** [comment]
Can you also consider sourcehut?

**Comment by TheOPtimal** [comment]
Why SourceHut? GNOME GitLab is the most obvious and logical place to move to.

**Comment by SeaDve** [comment]
started mirroring on gnome gitlab, as first step

**Comment by SeaDve** [comment]
I decided to keep Kooha repo on GitHub as the infrastructure are already set here, I believe that the migration efforts would outweight the benefits from moving to GitLab.
