### ISSUE TITLE
Distorted video on screen region recording

### ISSUE THREAD

**Issue by juxuanu** [SeaDve/Kooha#101]
https://streamable.com/paafl1

https://streamable.com/hrpobn

WebM nor MKV file formats make a difference.

Flatpak latest version.
Running it on the command line outputs nothing, so I don't know where to get logs from.

**Comment by SeaDve** [comment]
I don't like to fully support it yet since it is pretty buggy, so not yet on preferences. Plus it is pretty easy to run it with the envvar, and it is a signal that it is not something stable.

**Comment by juxuanu** [comment]
Alright, then. I'll wait for the next version and select mp4. Thanks.
