### ISSUE TITLE
Progress bar when processing

### ISSUE THREAD

**Issue by thomas-shirley** [SeaDve/Kooha#103]
Superb app!

When you've recorded a particularly long capture, the 'processing' screen can run for quite some time. A progress bar indicating how much more 'processing' is remaining, would be great.

**Comment by SeaDve** [comment]
thanks! Latest versions apps doesn't require processing anymore (except when cpu is trying to catch up with the encoder), so i think this is fixed

**Comment by thomas-shirley** [comment]
Nice. Which version is that? 

On version 1.2.1 I think the loading spinner ran for about 15-20 mins following a 2hr capture - Ryzen 5, Vega Graphics.  Not hugely powerful, so some cpu catch up is expected. But I started getting a little twitchy after 10 mins.

**Comment by SeaDve** [comment]
In the newest version, with vega graphics, even with that long video, i think it will just be less than a second of processing, so in theory it will end like nothing has happened.

The version btw is the latetst on git

**Comment by thomas-shirley** [comment]
I built and ran a little (but not very accurate) test with 1.2.1-838eb55

On 10 minute capture, the flushing process took approx. 6 minutes for a webm. Does that align with your expectations?

**Comment by SeaDve** [comment]
absolutely not, that shouldn't happen
