### ISSUE TITLE
Add option to record a specific window

### ISSUE THREAD

**Issue by zareami10** [SeaDve/Kooha#11]
It would be great if we could record a specif window. This might be more of an "upstream" issue but there appear to be some [workarounds](https://superuser.com/a/566727).

**Comment by SeaDve** [comment]
This workaround would only work for X11. There is a non-workaround way which uses freedesktop portal which is currently being worked on.

**Comment by jannuary** [comment]
> There is a non-workaround way which uses freedesktop portal which is currently being worked on.

Doesn't OBS have that implemented already?

**Comment by SeaDve** [comment]
> > There is a non-workaround way which uses freedesktop portal which is currently being worked on.
> 
> Doesn't OBS have that implemented already?

Yes

**Comment by jannuary** [comment]
> > > There is a non-workaround way which uses freedesktop portal which is currently being worked on.
> > 
> > 
> > Doesn't OBS have that implemented already?
> 
> Yes, I meant that I am currently working on implementing it here.

Ah, great to hear!

**Comment by SeaDve** [comment]
#65 working on specific window support :D 
You can try it but very buggy

**Comment by SeaDve** [comment]
Not buggy anymore

**Comment by SeaDve** [comment]
merged to main
