### ISSUE TITLE
Missing doap file

### ISSUE THREAD

**Issue by A6GibKm** [SeaDve/Kooha#110]
A `Kooha.doap` file is missing. Note that it has to have the same name/capitalization as the GitHub repository.

For the maintainer to appear in Apps for gnome it must be in the form

```xml
  <maintainer>
    <foaf:Person>
      <foaf:name>User Name</foaf:name>
      <foaf:mbox rdf:resource="mailto:user-email@emailprovider.org" />
      <gnome:userid>gnome-user-acc</gnome:userid>
      <foaf:account>
        <foaf:OnlineAccount>
            <foaf:accountServiceHomepage rdf:resource="https://github.com/"/>
            <foaf:accountName>user-github-acc</foaf:accountName>
        </foaf:OnlineAccount>
      </foaf:account>
    </foaf:Person>
  </maintainer>
```

**Comment by SeaDve** [comment]
I wonder why it is not showing in apps.gnome.org 
I'm suspecting the github repo name

**Comment by A6GibKm** [comment]
> I wonder why it is not showing in [apps.gnome.org](https://apps.gnome.org )
> I'm suspecting the github repo name

Yeah, it should be capitalized the same as the repo. And then Apps for GNOME needs a rebuild.

**Comment by SeaDve** [comment]
thanks!
