### ISSUE TITLE
No sound recorded with bluetooth headset

### ISSUE THREAD

**Issue by supremesyntax** [SeaDve/Kooha#111]
pactl list sources | grep "Name:"
	Name: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
	Name: alsa_input.pci-0000_00_1f.3.analog-stereo
	Name: bluez_sink.F0_A9_68_29_34_A8.a2dp_sink.monitor

A setting would be nice to choose the source.

**Comment by SeaDve** [comment]
It should pick the default source from your device. Changing it device wide, should also affect Kooha's

**Comment by SeaDve** [comment]
I'll close this issue since it is out of scope of the app
