### ISSUE TITLE
2.0 doesn't work on Fedora 34 KDE

### ISSUE THREAD

**Issue by pizzadude** [SeaDve/Kooha#119]
```
flatpak run io.github.seadve.Kooha
                                                                              
(kooha:2): Gdk-WARNING **: 08:56:56.717: Server is missing xdg_foreign support
```

That message shows up when I click the "record" button.

Here is system info info:

Operating System: Fedora 34
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.13.19-200.fc34.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-7300U CPU @ 2.60GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620

**Comment by SeaDve** [comment]
Try restarting, anyway, it might also not work properly, if it does work after that, see #60

**Comment by pizzadude** [comment]
> Try restarting, anyway, it might also not work properly, if it does work after that, see #60

I have all the needed system dependencies.

**Comment by pizzadude** [comment]
BTW this program never worked in KDE for me, previous versions crashed when recording, this version doesn't start recording at all due to that error I mentioned above.

I tried restarting but that didn't fix the problem, obviously.

**Comment by SeaDve** [comment]
feel free to submit a pr

**Comment by SeaDve** [comment]
I'll close this in favor of #60
