### ISSUE TITLE
Toggle button state hard to discern

### ISSUE THREAD

**Issue by lightonflux** [SeaDve/Kooha#124]
**System Info**
- Kooha version: 2.0.0
- Distro information: Fedora 34 Workstation
- Desktop Environment information and version: GNOME 40.4
- Display Server: wayland
- Flatpak: yes

**Describe the bug**
With the new adwaita theme the toggle button state is hard to see. Especially on bad displays. 
![Bildschirmfoto von 2021-09-25 18-57-19_is_on?](https://user-images.githubusercontent.com/1377943/134780084-e8bfc548-fa31-4a6f-990d-0cf8df5a925c.png)

**To Reproduce**
1. Install 2.0
2. toggle buttons

**Expected behavior**
It should be very easy to see which state the buttons are in.

**Suggestions**
* Remove button outline when disabled (like with the 3 dashes button in the top left corner).
* Or change icon colour when enabled. 
* Change button colour completely  (not two different shades of the same colour.)

![Bildschirmfoto von 2021-09-25 18-57-19_bg](https://user-images.githubusercontent.com/1377943/134780124-69538d57-35c2-4a23-8605-e6c9434aeaae.png)
![Bildschirmfoto von 2021-09-25 18-57-19_true_bg](https://user-images.githubusercontent.com/1377943/134780126-11e8d9e1-a089-4713-9f5b-a7ea1688e8cf.png)

**Comment by SeaDve** [comment]
I do have the same problem, but I don't like changing the stylesheet much downstream. I think this should be fixed on the libadwaita itself. See https://gitlab.gnome.org/GNOME/libadwaita/-/issues/228 too

**Comment by SeaDve** [comment]
My temporary solution is to change the icon to show something like a slash when it is turned of, but not sure if it will look good

**Comment by SeaDve** [comment]
what about something like this?
![image](https://user-images.githubusercontent.com/64297935/135696684-c21bde1e-8879-4d7e-9359-78ff3051cdef.png)

**Comment by SeaDve** [comment]
The latest release from libadwaita kinda fixes this by increasing the contrast diff between two states

**Comment by danastasio** [comment]
It's honestly extremely hard to tell the difference between the two states still.

**Comment by SeaDve** [comment]
![image](https://user-images.githubusercontent.com/64297935/184589887-9ad6169e-8ba0-44ff-b02e-0d8b1deabbe0.png)

Fixed on master
