### ISSUE TITLE
Feature request: make GIFs loop

### ISSUE THREAD

**Issue by Hofer-Julian** [SeaDve/Kooha#127]
GIFs can be told within the metadata whether they should loop or not (even the number of loops is possible)
As far as I can tell, most people would expect their GIFs to loop.
This is why I suggest to change the current behaviour, which is letting the sequence only run a single time.

**Comment by SeaDve** [comment]
I also think that's a better behavior, so setting it that

**Comment by Hofer-Julian** [comment]
Thanks a lot!

Awesome app btw 😊

**Comment by SeaDve** [comment]
thanks! :D
