### ISSUE TITLE
Export in real time to program like Jami

### ISSUE THREAD

**Issue by ovari** [SeaDve/Kooha#131]
Can Kooha export in real time to another program like [Jami](https://jami.net/).

This would enable the following features in Jami:
* [Window sharing](https://git.jami.net/savoirfairelinux/jami-project/-/issues/1294).
* Hide or show mouse pointer.
* Record your microphone, computer sounds, or both at the same time.

Thank you

**Comment by SeaDve** [comment]
Thanks for reporting! I'm closing this as out of scope. Jami could implement the same way Kooha does, accessing the `org.freedesktop.portal.ScreenCast` interface, then handle the pipewire streams much more freely and efficient than with integrating with Kooha.
