### ISSUE TITLE
distro based dependency - xdg-desktop-portal-wlr - can't record

### ISSUE THREAD

**Issue by fastrizwaan** [SeaDve/Kooha#133]
**System Info**
- Kooha version **2.0.1**
- Distro information and version: **Solus 4.3**
- Desktop Environment information and version: **GNOME 41**
- Display Server: **X11**
- Flatpak? **Yes!**

**Describe the bug**
![image](https://user-images.githubusercontent.com/1161682/138086268-df4047a2-6cc9-4028-a978-6c3dda3ea636.png)

Screen cast portal error

**To Reproduce**
1. Install kooha in Solus 4.3 (https://getsol.us/home/)
2. Click on '....' Record then "Select Monitor" and "Share"
3. See error (screenshot above)

**Expected behavior**
Recording should work. If flatpaked app starts to depend on distro provided packages, then the idea of distro-agnostic approach is failed. Please avoid distro specific dependencies.

**Comment by arpu** [comment]
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer.

any info what i need change for fedora 34?
