### ISSUE TITLE
No x264enc

### ISSUE THREAD

**Issue by starsareintherose** [SeaDve/Kooha#136]
**System Info**
- Kooha version 2.0.1
- Distro information and version: ArchLinux
- Desktop Environment information and version GNOME 40.5
- Display Server Wayland
- AUR

**Describe the bug**
When I want to save recording as mp4 format
```
No x264enc
Help: A GStreamer plugin may not be installed. If not, please report to Kooha's issue page.
````

**To Reproduce**
1. Go to 'Video format'
2. Click on 'mp4'
3. See error above

**Expected behavior**
can save mp4

**Additional context**
If applicable, please attach the logs from running Kooha with the following 
environment variables `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3`
while running kooha (e.g. `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 flatpak run io.github.seadve.Kooha`)

**Comment by SeaDve** [comment]
check if you have `gstreamer-plugins-ugly` installed

**Comment by starsareintherose** [comment]
No, I will comment to the AUR maintainer
