### ISSUE TITLE
I get this when building with yay

### ISSUE THREAD

**Issue by roktcode** [SeaDve/Kooha#137]
**Screenshots**
https://i.imgur.com/ndHGJax.png

**Additional context**
error: could not compile `kooha` due to previous error
[3/4] Generating io.github.seadve..._data_merge with a custom command
FAILED: src/kooha 
/bin/sh /home/myasso/.cache/yay/kooha/src/Kooha-2.0.1/build-aux/cargo.sh /home/myasso/.cache/yay/kooha/src/build /home/myasso/.cache/yay/kooha/src/Kooha-2.0.1 src/kooha '' kooha
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
error making: kooha

**Comment by SeaDve** [comment]
does your setup support scripts with `#!/bin/sh`?

**Comment by roktcode** [comment]
> does your setup support scripts with `#!/bin/sh`?

I am using GNOME terminal. Is that what you mean?

**Comment by mnme** [comment]
I'm probably running into the same problem, but it already fails much earlier in the build.

```
error[E0658]: `cfg(doctest)` is experimental and subject to change
 --> /home/username/.cache/yay/kooha/src/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/xml-rs-0.8.4/src/lib.rs:9:7
  |
9 | #[cfg(doctest)]
  |       ^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/62210

error[E0658]: `cfg(doctest)` is experimental and subject to change
  --> /home/username/.cache/yay/kooha/src/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/xml-rs-0.8.4/src/lib.rs:13:7
   |
13 | #[cfg(doctest)]
   |       ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/62210

   Compiling fastrand v1.5.0
   Compiling parking v2.0.0
   Compiling event-listener v2.5.1
   Compiling lazy_static v1.4.0
   Compiling pretty-hex v0.2.1
   Compiling byteorder v1.4.3
   Compiling temp-dir v0.1.11
   Compiling paste v1.0.5
   Compiling ppv-lite86 v0.2.10
   Compiling cc v1.0.70
   Compiling muldiv v1.0.0
   Compiling static_assertions v1.1.0
   Compiling scoped-tls v1.0.0
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `xml-rs`.
warning: build failed, waiting for other jobs to finish...
error: build failed
[36/37] Generating data/io.github.seadve.Kooha.metainfo.xml with a custom command
FAILED: src/kooha 
/bin/sh /home/username/.cache/yay/kooha/src/Kooha-2.0.1/build-aux/cargo.sh /home/username/.cache/yay/kooha/src/build /home/username/.cache/yay/kooha/src/Kooha-2.0.1 src/kooha '' kooha
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: kooha
```

**Comment by SeaDve** [comment]
> I'm probably running into the same problem, but it already fails much earlier in the build.
> 
> ```
> error[E0658]: `cfg(doctest)` is experimental and subject to change
>  --> /home/username/.cache/yay/kooha/src/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/xml-rs-0.8.4/src/lib.rs:9:7
>   |
> 9 | #[cfg(doctest)]
>   |       ^^^^^^^
>   |
>   = note: for more information, see https://github.com/rust-lang/rust/issues/62210
> 
> error[E0658]: `cfg(doctest)` is experimental and subject to change
>   --> /home/username/.cache/yay/kooha/src/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/xml-rs-0.8.4/src/lib.rs:13:7
>    |
> 13 | #[cfg(doctest)]
>    |       ^^^^^^^
>    |
>    = note: for more information, see https://github.com/rust-lang/rust/issues/62210
> 
>    Compiling fastrand v1.5.0
>    Compiling parking v2.0.0
>    Compiling event-listener v2.5.1
>    Compiling lazy_static v1.4.0
>    Compiling pretty-hex v0.2.1
>    Compiling byteorder v1.4.3
>    Compiling temp-dir v0.1.11
>    Compiling paste v1.0.5
>    Compiling ppv-lite86 v0.2.10
>    Compiling cc v1.0.70
>    Compiling muldiv v1.0.0
>    Compiling static_assertions v1.1.0
>    Compiling scoped-tls v1.0.0
> error: aborting due to 2 previous errors
> 
> For more information about this error, try `rustc --explain E0658`.
> error: could not compile `xml-rs`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> [36/37] Generating data/io.github.seadve.Kooha.metainfo.xml with a custom command
> FAILED: src/kooha 
> /bin/sh /home/username/.cache/yay/kooha/src/Kooha-2.0.1/build-aux/cargo.sh /home/username/.cache/yay/kooha/src/build /home/username/.cache/yay/kooha/src/Kooha-2.0.1 src/kooha '' kooha
> ninja: build stopped: subcommand failed.
> ==> ERROR: A failure occurred in build().
>     Aborting...
>  -> error making: kooha
> ```

You likely have older version of rustc or cargo.

**Comment by SeaDve** [comment]
Is this still reproducible in main branch?

**Comment by roktcode** [comment]
hello there it has been a while since i posted this. but right now kooha works just fine i'm using latest GNOME with EndeavourOS an I think i have no problem now. thank you
