### ISSUE TITLE
sound from desktop/system/monitor not recorded

### ISSUE THREAD

**Issue by fastrizwaan** [SeaDve/Kooha#14]
Hi, 
Just discovered Kooha at flathub, really liked it, but it is not recording audio playback in the system. I use simplescreenrecorder, which shows Audio Recording Source and records audio.
![recording](https://user-images.githubusercontent.com/1161682/111293203-06e38d00-866f-11eb-964a-8f115dfa9452.png)

Thank you.

**Comment by SeaDve** [comment]
Thanks for reporting the bug. May you run this command in the terminal? `pactl list sources | grep "Name:"`
This command should output your sound devices.

**Comment by fastrizwaan** [comment]
> Thanks for reporting the bug. May you run this command in the terminal? `pactl list sources | grep "Name:"`
> This command should output your sound devices and maybe paste it here.

```
rizvan@debian:~$ pactl list sources | grep "Name:"
	Name: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
	Name: alsa_input.pci-0000_00_1b.0.analog-stereo

```

**Comment by fastrizwaan** [comment]
It's working, thanks.

**Comment by SeaDve** [comment]
I think I found the issue, I programmed the app to get the last plugged in source, so it might be getting the output from the HDMI source, instead of the actual output. This should be an easy fix but might change the behavior for other people.

**Comment by SeaDve** [comment]
I'll be pushing the fix on master

**Comment by fastrizwaan** [comment]
```
$ pactl list sources | grep "Name:"
	Name: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
	Name: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1.monitor
```

**Comment by SeaDve** [comment]
Yeah, that must be it, I already pushed the fix in master, and might take a while to update in Flathub.

**Comment by SeaDve** [comment]
Hi, the fix is now available in flatpak, feel free to close the issue when it is resolved.

**Comment by fastrizwaan** [comment]
Yes, sound is recorded now, Thank you!
