### ISSUE TITLE
Pipeline-Build error when tying to record screen area

### ISSUE THREAD

**Issue by shrugal** [SeaDve/Kooha#141]
**System Info**
- Kooha version: 2.0.1
- Distro information and version: Fedora 35
- Desktop Environment information and version: GNOME 41.1
- Display Server: X11
- Flatpak: 1.12.2
- Graphics card: Nvidia GeForce RTX 3070 Ti with driver version 495.44
- Monitors: 2560x1440 and 1920x1080

**Describe the bug**
Trying to record a portion of the screen fails with the following error message (translated from German):

*Pipeline-Build Error*
videoscale0 could not be linked to videocrop0. videocrop0 cannot handle capital letters video/x-raw, width=(int)1920, height=(int)1080.

**To Reproduce**
1. Select "Record display area"
2. Disable PC audio and microphone recording, enable mouse recording
3. Click "Record"
4. Choose to share main monitor
5. Select an area to record
6. Error message above appears

**Expected behavior**
It should start recording the selected area.

**Additional context**
```
Nov 21 13:14:54 pc-linux systemd[2009]: Started app-flatpak-io.github.seadve.Kooha-37058.scope.
Nov 21 13:14:54 pc-linux gnome-shell[22380]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x5800004
Nov 21 13:14:59 pc-linux gnome-shell[22380]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x92274692 specified for 0x4800021.
Nov 21 13:15:02 pc-linux io.github.seadve.Kooha.desktop[35126]:  ERROR kooha::backend::recorder > Failed to build pipeline: Error { domain: gst_parse_error, code: 3, message: "videoscale0 konnte nicht mit videocrop0 verknüpft werden. videocrop0 kann nicht mit Großbuchstaben video/x-raw, width=(int)1920, height=(int)1080 umgehen" }
Nov 21 13:15:31 pc-linux gnome-shell[24820]: [24859:24859:1121/131531.171734:ERROR:shared_image_manager.cc(214)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
Nov 21 13:15:31 pc-linux gnome-shell[24820]: [24859:24859:1121/131531.172302:ERROR:shared_image_manager.cc(214)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
```

(This is all I could find)

**Comment by SeaDve** [comment]
Does the same thing happen when on normal one?

**Comment by shrugal** [comment]
What do you mean by normal one?

**Comment by SeaDve** [comment]
This mode
![image](https://user-images.githubusercontent.com/64297935/146327264-a25d09b7-5564-4d41-9ec4-8c4c81ba9a58.png)

**Comment by brunomcuesta** [comment]
Same problem here when I tried to record screen area, but other configuration en output error. The app fails to record the video in mp4 saying the path to the directory does not exist. I'm trying to save to my home and the directory doesn't have accents.

- Kooha version: 2.0.1
- Distro information and version: Debian 11
- Desktop Environment information and version: GNOME 3.38.5
- Display Server: Wayland
- Flatpak: 1.10.5
- Monitor: 1366x768

Log:

```
Dec 20 20:32:26 debian io.github.seadve.Kooha.desktop[3950]:  ERROR kooha::backend::recorder::imp > Failed to set pipeline state to Playing: StateChangeError
Dec 20 20:32:26 debian io.github.seadve.Kooha.desktop[3950]:  ERROR kooha::backend::recorder      > Error from record bus: Error { domain: gst-resource-error-quark, code: 1, message: "stream error: wrong resource type/version" } (debug Error(Message { ptr: 0x55c9d4d62420, type: "error", seqnum: 115, src: Some("pipewiresrc0"), structure: Some(GstMessageError, gerror=(GError)NULL, debug=(string)"../src/gst/gstpipewiresrc.c\(529\):\ on_state_changed\ \(\):\ /GstPipeline:pipeline0/GstPipeWireSrc:pipewiresrc0";) }))
```

**Comment by shrugal** [comment]
> This mode ![image](https://user-images.githubusercontent.com/64297935/146327264-a25d09b7-5564-4d41-9ec4-8c4c81ba9a58.png)

That mode works fine.

**Comment by SeaDve** [comment]
> Same problem here when I tried to record screen area, but other configuration en output error. The app fails to record the video in any format saying the path to the directory does not exist. I'm trying to save to my home and the directory doesn't have accents.
> 
>     * Kooha version: 2.0.1
> 
>     * Distro information and version: Debian 11
> 
>     * Desktop Environment information and version: GNOME 3.38.5
> 
>     * Display Server: Wayland
> 
>     * Flatpak: 1.10.5
> 
>     * Monitor: 1366x768
> 
> 
> Log:
> 
> ```
> Dec 20 20:32:26 debian io.github.seadve.Kooha.desktop[3950]:  ERROR kooha::backend::recorder::imp > Failed to set pipeline state to Playing: StateChangeError
> Dec 20 20:32:26 debian io.github.seadve.Kooha.desktop[3950]:  ERROR kooha::backend::recorder      > Error from record bus: Error { domain: gst-resource-error-quark, code: 1, message: "stream error: wrong resource type/version" } (debug Error(Message { ptr: 0x55c9d4d62420, type: "error", seqnum: 115, src: Some("pipewiresrc0"), structure: Some(GstMessageError, gerror=(GError)NULL, debug=(string)"../src/gst/gstpipewiresrc.c\(529\):\ on_state_changed\ \(\):\ /GstPipeline:pipeline0/GstPipeWireSrc:pipewiresrc0";) }))
> ```

This is likely unrelated to this issue, check out #129

**Comment by SeaDve** [comment]
> > This mode ![image](https://user-images.githubusercontent.com/64297935/146327264-a25d09b7-5564-4d41-9ec4-8c4c81ba9a58.png)
> 
> That mode works fine.

Sorry for the very late response.

Could you show the output of the following commands? `gst-inspect-1.0  videoscale` & `gst-inspect-1.0 videocrop` after you ran `flatpak run --command=sh io.github.seadve.Kooha`

**Comment by SeaDve** [comment]
Closing this as stale. Please feel free to reopen the issue if the requested information is provided. Thanks!
