### ISSUE TITLE
provide the ability to specify the frame rate within the UI

### ISSUE THREAD

**Issue by YousefSaber** [SeaDve/Kooha#142]
can you please in a future release provide an option within the app to specify the frame rate of the recording whether it's 30FPS or 60FPS?

**Comment by SeaDve** [comment]
The 60fps one is currently buggy for some device, so won't expose it to the UI for now

**Comment by SeaDve** [comment]
> The 60fps one is currently buggy for some device, so won't expose it to the UI for now

This has been fixed.

Also, there will be an option to specify the frame rate in the UI when  `2.1.2` is released. However, it would be behind a `KOOHA_EXPERIMENTAL` env var that must be set to `1`.
