### ISSUE TITLE
Invisible cursor problem (while vscode is fullscreen)

### ISSUE THREAD

**Issue by Ojvar** [SeaDve/Kooha#144]
Hi

I've faced with a problem while recording my screen by kooha
My cursor goes invisible when I tried to record my vscode screen in fullscreen mode, it' just hide the cursor from me, but when I review my recorded video, the cursor were visible

**Comment by SeaDve** [comment]
could you provide the extra informations, information from the issue template

**Comment by SeaDve** [comment]
https://github.com/SeaDve/Kooha/issues/56
