### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by luis-alves** [SeaDve/Kooha#150]
**System Info**
Version: 2.0.1
Distro: Fedora silverblue 35
DE: Gnome 41
DS: Wayland with Pipewire
packaging: Flatpak

**Describe the bug**
The app misses two icons (see image)

**To Reproduce**

Open app

**image:**
![image](https://user-images.githubusercontent.com/16962593/149367597-f9201d21-e95c-4daf-8a72-f579112f6e22.png)

**Expected behavior**
All icons should be visable

**Comment by SeaDve** [comment]
I guess we should bundle the icons, since it seems not all distro provide those icons

**Comment by luis-alves** [comment]
Well they just appeared. Don't ask me how!
![image](https://user-images.githubusercontent.com/16962593/149632624-83e61f1c-74c7-4528-bd11-76e873db70c6.png)

**Comment by airtonix** [comment]
> Well they just appeared. Don't ask me how! ![image](https://user-images.githubusercontent.com/16962593/149632624-83e61f1c-74c7-4528-bd11-76e873db70c6.png)

You probably did something that changed the icons your current theme declares it should use.

I can see in the first image that it looks like the font you're using is different from the second screenshot.

Did you change your theme in between the two screenshots ?
