### ISSUE TITLE
Use AV1 format, deprecate previous-gen VP8 codec

### ISSUE THREAD

**Issue by heyakyra** [SeaDve/Kooha#151]
Sadly, the Daala codec hasn't had it's breakthrough adoption yet, but in the meantime AV1 is enjoying mainstream adoption. 

It's much more efficient https://www.streamingmedia.com/Articles/Editorial/Featured-Articles/AV1-A-First-Look-127133.aspx

**Comment by darkguy2008** [comment]
@SeaDve hey, maybe unrelated, but I'm getting the usual "`no element "vaapivp8enc"`" error. **However**, on my system I get this:
```
gst-inspect-1.0 | grep -i vaapi
vaapi:  vaapiav1dec: VA-API AV1 decoder
vaapi:  vaapidecodebin: VA-API Decode Bin
vaapi:  vaapih264dec: VA-API H264 decoder
vaapi:  vaapih264enc: VA-API H264 encoder
vaapi:  vaapih265dec: VA-API H265 decoder
vaapi:  vaapih265enc: VA-API H265 encoder
vaapi:  vaapijpegdec: VA-API JPEG decoder
vaapi:  vaapijpegenc: VA-API JPEG encoder
vaapi:  vaapimpeg2dec: VA-API MPEG2 decoder
vaapi:  vaapimpeg2enc: VA-API MPEG-2 encoder
vaapi:  vaapioverlay: VA-API overlay
vaapi:  vaapipostproc: VA-API video postprocessing
vaapi:  vaapisink: VA-API sink
vaapi:  vaapivc1dec: VA-API VC1 decoder
vaapi:  vaapivp9dec: VA-API VP9 decoder
vaapi:  vaapivp9enc: VA-API VP9 encoder
```
I see my machine seems to have a VP9 encoder instead of VP8. How hard would it be to add an argument or env variable to Kooha or something that'll allow me to set up the encoder to use instead?

**Comment by SeaDve** [comment]
> How hard would it be to add an argument or env variable to Kooha or something that'll allow me to set up the encoder to use instead? 

That would be simple. However, that's not the long term solution I'm going for

**Comment by SeaDve** [comment]
For what's it worth, I've been working on allowing user to specify muxer, audio & video encoder, and other stuff:
https://github.com/SeaDve/Kooha/pull/178

**Comment by SeaDve** [comment]
Experimental VP9 + WebM profile is now merged on main, and AV1 is also added (can crash). These could be enabled via `KOOHA_EXPERIMENTAL=1` env arg.

**Comment by heyakyra** [comment]
I tried to record a <10second clip. When I started recording, the length counter never increased from "Paused 00:00" in Kooha, but when I hit stop recording it said "Flushing" for a long time and the file size grew to ~1.5MB before this error popped up and the file was automatically erased:

```
An error occurred while recording

Caused by:
    0: ../plugins/elements/gstqueue.c(992): gst_queue_handle_sink_event (): /GstPipeline:pipeline3/GstBin:bin3/GstQueue:queue5:
       streaming stopped, reason error (-5)
    1: Internal data stream error.
```

**Comment by SeaDve** [comment]
May you show the full logs with RUST_LOG=debug?

**Comment by lamyergeier** [comment]
> Experimental VP9 + WebM profile is now merged on main, and AV1 is also added (can crash). These could be enabled via KOOHA_EXPERIMENTAL=1 env arg.


The recorded video till uses VP8. Is this the correct way to use AV1?

```
$ KOOHA_EXPERIMENTAL=1 flatpak run io.github.seadve.Kooha
2024-02-19T20:24:14.683448Z  INFO kooha::application: Kooha (io.github.seadve.Kooha)
2024-02-19T20:24:14.683469Z  INFO kooha::application: Version: 2.2.4 ()
2024-02-19T20:24:14.683473Z  INFO kooha::application: Datadir: /app/share/kooha
```

**Comment by lamyergeier** [comment]
> Experimental VP9 + WebM profile is now merged on main, and AV1 is also added (can crash). These could be enabled via `KOOHA_EXPERIMENTAL=1` env arg.

The recorded video till uses VP8. Is this the correct way to use AV1?

```
$ KOOHA_EXPERIMENTAL=1 flatpak run io.github.seadve.Kooha
2024-02-19T20:24:14.683448Z  INFO kooha::application: Kooha (io.github.seadve.Kooha)
2024-02-19T20:24:14.683469Z  INFO kooha::application: Version: 2.2.4 ()
2024-02-19T20:24:14.683473Z  INFO kooha::application: Datadir: /app/share/kooha
```

**Comment by SeaDve** [comment]
> > Experimental VP9 + WebM profile is now merged on main, and AV1 is also added (can crash). These could be enabled via `KOOHA_EXPERIMENTAL=1` env arg.
> 
> The recorded video till uses VP8. Is this the correct way to use AV1?
> 
> ```
> $ KOOHA_EXPERIMENTAL=1 flatpak run io.github.seadve.Kooha
> 2024-02-19T20:24:14.683448Z  INFO kooha::application: Kooha (io.github.seadve.Kooha)
> 2024-02-19T20:24:14.683469Z  INFO kooha::application: Version: 2.2.4 ()
> 2024-02-19T20:24:14.683473Z  INFO kooha::application: Datadir: /app/share/kooha
> ```

Yes, but you also have to install the necessary plugins and change it on the preferences.
