### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by uninhm** [SeaDve/Kooha#152]
- Kooha version 2.0.1
- Void Linux

I get
`meson.build:17:0: ERROR: Invalid version of dependency, need 'libadwaita-1' ['>= 1.0.0-alpha.1'] found '1.0.0'.`

And I think those versions are meant to be the same (or even the one I have could be newer, because it's not alpha, IDK actually)

**Comment by SeaDve** [comment]
try git pulling

**Comment by uninhm** [comment]
@SeaDve The fact is that I'm packaging Kooha for Void Linux, I have to use a release...

**Comment by SeaDve** [comment]
you can force it by changing the required version in meson.build
