### ISSUE TITLE
Use yyyy-mm-dd in filenames for easy lexical sorting

### ISSUE THREAD

**Issue by Vinnl** [SeaDve/Kooha#154]
**System Info**
- Kooha version: 2.0.1
- Distro information and version (Fedora 34 Workstation, etc.): Fedora 35 Workstation
- Desktop Environment information and version (GNOME 41, etc.): GNOME 41.3
- Display Server (Wayland, etc.): Wayland
- Flatpak: Yes

Currently, videos saved by Kooha have a filename like `Kooha-mm-dd-yyyy-hh-mm-ss.mimetype`. Besides there only being few countries that mention the month first, this also makes it harder to find the most recent recording when looking through your files sorted by filename, as is the default in many filemanagers.

An unambiguous alternative (i.e. understood throughout the world) that also makes the lexical order equal to the chronological order would be to use `Kooha-yyyy-mm-dd-hh-mm-ss.mimetype`.

**Comment by SeaDve** [comment]
This has been changed now in main since https://github.com/SeaDve/Kooha/pull/146

**Comment by Vinnl** [comment]
Oh ha, great minds think alike - thanks!
