### ISSUE TITLE
Add a pin icon to quickly make Kooha on top of all windows

### ISSUE THREAD

**Issue by ghost** [SeaDve/Kooha#156]
GNOME allows a window to be on top of others by right clicking in the titlebar/headerbar, but it would be nicer if Kooha displayed a pin icon to better indicate that this is possible.

**Comment by SeaDve** [comment]
It was possible before with hacks through gnome-shell eval interface, but it is now not possible since gnome-shell 41 where it became a private interface. Unless, there a portal interface is made

**Comment by SeaDve** [comment]
Closing this as out of scope.
