### ISSUE TITLE
Hours not being displayed

### ISSUE THREAD

**Issue by feimosi** [SeaDve/Kooha#161]
**System Info**
- Kooha version 2.0.1
- Distro information and version EndeavourOS (Arch)
- Desktop Environment information and version GNOME 41
- Display Server X11
- Flatpak? No

**Describe the bug**
When the recording duration starts to take an hour or more, the hours part is cut off and not visible in the UI. It only displays MM:SS format.

**To Reproduce**
Record a video longer than 59:59

**Expected behavior**
Display the time in the format HH:MM:SS when relevant.

**Screenshots**
This can't be captured on a screenshot.

**Additional context**
No

**Comment by SeaDve** [comment]
This is now fixed on https://github.com/SeaDve/Kooha/commit/32dae32d10d507c448a7cc2d63bc68b5dddfebda. However, it would still be formatted as `MM:SS` but just increase to `60:00`.

**Comment by SeaDve** [comment]
We would show `HH` on future redesigns to address also other issues.
