### ISSUE TITLE
 Is there a way  to make start Kooha with hardware acceleration enabled?

### ISSUE THREAD

**Issue by Cherro59** [SeaDve/Kooha#166]
**System Info**
- Distro information and version (Fedora 35 Workstation)
- Desktop Environment information and version (GNOME 42.)
- Display Server (Wayland)
- Builded by myself

Yes I can do it by launching it via terminal with **GST_VAAPI_ALL_DRIVERS=1 KOOHA_VAAPI=1** flags. But I don't want to always open terminal to make it  use less cpu. I tried edit desktop entry but here is no success. After edit Kooha disappears from app list

**Comment by SeaDve** [comment]
You can use flatseal to always set those variables on start up

**Comment by SeaDve** [comment]
Closing this as out of scope. Ideally, if vaapi is much more stable, it would be on the UI.
