### ISSUE TITLE
Kooha freezing when recording microphone audio

### ISSUE THREAD

**Issue by ArnaudLier** [SeaDve/Kooha#167]
**System Info**
- Kooha version **2.0.1**
- Distro information and version **Fedora 36 Silverblue**
- Desktop Environment information and version **GNOME 42.2**
- Display Server **Wayland**
- Flatpak? **Yes**

**Describe the bug**
When starting a record with microphone audio enabled, Kooha will freeze and the "Kooha is not responding" popup will appear. After a few moments clicking on "Wait", Kooha finally starts the recording but stopping the record freezes Kooha for good (I've waited some time and it's still not unfreezing).

**To Reproduce**
1. Select whatever options you want _but_ with microphone audio enabled.
2. Start recording
3. Contemplate the beauty of the universe while waiting for Kooha to unfreeze.

**Expected behavior**
Be able to record microphone audio without problems.

**Additional context**

Depending on the run, different types of errors occured, each code block is one run of the program. On the two last runs, the recording screen with actual time didn't show up at all.
```
 ERROR kooha::backend::recorder          > Error from record bus: Error { domain: gst-resource-error-quark, code: 1, message: "Failed to connect stream: Timeout" } (debug Error(Message { ptr: 0x7f9034001880, type: "error", seqnum: 641, src: Some("pulsesrc1"), structure: Some(GstMessageError, gerror=(GError)NULL, debug=(string)"../ext/pulse/pulsesrc.c\(1619\):\ gst_pulsesrc_prepare\ \(\):\ /GstPipeline:pipeline2/GstPulseSrc:pulsesrc1";) }))
```
```
ERROR kooha::backend::screencast_portal > Error from screencast call: Portal(ZBus(MethodError(OwnedInterfaceName(InterfaceName(Str("org.freedesktop.DBus.Error.Failed"))), Some("No node factory discovered"), Msg { type: Error, sender: UniqueName(Str(":1.83")), reply-serial: 37, body: Signature: [
	s (115),
] })))
```
```
** (process:63115): WARNING **: 20:25:54.180: Invalid client serial
(kooha:2): Gdk-CRITICAL **: 20:26:11.802: gdk_wayland_toplevel_export_handle: assertion '!wayland_toplevel->xdg_exported' failed
```

**Comment by ArnaudLier** [comment]
I think the problem also killed Firefox as it wasn't responding during some of my runs. Restarted my system and now Kooha seems to work fine :thinking:

**Comment by Julioevm** [comment]
I've started to find this isue with the freezes in the mic recording, but video seems fine. And Im not getting any Kooha is not responding, but mic seems to get progressively worse.

**Comment by SeaDve** [comment]
Thanks for reporting! Closing this then since it was not an issue within Kooha.

**Comment by SeaDve** [comment]
> I've started to find this isue with the freezes in the mic recording, but video seems fine. And Im not getting any Kooha is not responding, but mic seems to get progressively worse.

This may be that issue https://github.com/SeaDve/Kooha/issues/106
