### ISSUE TITLE
kooha can't select specific window

### ISSUE THREAD

**Issue by starsareintherose** [SeaDve/Kooha#168]
**System Info**
- Kooha version 2.0.1-3
- Distro information and version: Arch Linux
- Desktop Environment information and version: wayfire WM 0.7.3
- Display Server Wayland
- Flatpak? NA

**Describe the bug**
can't select the specific windows
```
(kooha:109192): Gdk-WARNING **: 16:45:41.479: Compositor doesn't support moving popups, relying on remapping
```
maybe related to this

**To Reproduce**
1. Go to main page
2. Click on screencast with windows button
3. See error

**Expected behavior**
can screencast specific windows on wayfire

**Screenshots**

**Additional context**
If applicable, please attach the logs from running Kooha with the following 
environment variables `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3`
while running kooha (e.g. `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 flatpak run io.github.seadve.Kooha`)

**Comment by SeaDve** [comment]
wayfire likely doesn't support selecting specific window, and kooha probably can't do anything about it. Unless if other apps that uses the screencast portal, like firefox, allows it

**Comment by starsareintherose** [comment]
okay, thanks
