### ISSUE TITLE
Kooha looks broken

### ISSUE THREAD

**Issue by orangebowlerhat** [SeaDve/Kooha#169]
**System Info**
- Kooha version 2.0.1-3
- Manjaro
- XFCE
- X11
- AUR

**Describe the bug**
I just installed Kooha to try it but it looks very odd on my desktop. See image below.

**To Reproduce**
Run Kooha

**Expected behavior**
Looking less odd?

**Screenshots**
![image](https://user-images.githubusercontent.com/12849146/177645659-dc6d8163-0402-467e-bc47-d7f2761a428e.png)

**Comment by orangebowlerhat** [comment]
Hello SeaDve,

It seems so. I just got an update for Galculator that looks like this too. Is there a version of Kooha that doesn't use GTK4?

**Comment by SeaDve** [comment]
Yes, but it was before v2.0 and unsupported.

**Comment by SeaDve** [comment]
Thanks for reporting! Closing this as an external issue

**Comment by orangebowlerhat** [comment]
Thanks for making the effort to respond. I appreciate that time is a precious resource and that you give it freely.
