### ISSUE TITLE
Doesn't record in Ubuntu 20.10

### ISSUE THREAD

**Issue by liimee** [SeaDve/Kooha#17]
Video:
https://files.catbox.moe/0e7e2r.mp4
fyi, I'm using Ubuntu 20.10 if that helps

anyways, cool app :D
thanks in advance!

**Comment by SeaDve** [comment]
This is a problem with Ubuntu 20.10 packaging. For more information, you can check [this](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1901391).

Running it through terminal `flatpak run io.github.seadve.Kooha` should also give more information about the error.

**Comment by SeaDve** [comment]
The output of flatpak run would still be helpful though since it might be a different issue.

**Comment by CODESOLE** [comment]
yeah that happens me as well here is the output from the terminal:

```
Detected sources: ['alsa_output.pci-0000_00_1f.3.analog-stereo.monitor', '']
Detected sources: ['alsa_input.pci-0000_00_1f.3.analog-stereo', '']
Traceback (most recent call last):
  File "/app/share/kooha/kooha/window.py", line 126, in on_stop_record_button_clicked
    self.video_recorder.stop()
  File "/app/share/kooha/kooha/recorders.py", line 166, in stop
    self.GNOMEScreencast.call_sync(
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.Screencast was not provided by any .service files (2)

```

**Comment by SeaDve** [comment]
> probably ubuntu did not integrate flatpak properl

This seems a packaging issue, should be fix in 21.04; Thanks!

**Comment by liimee** [comment]
alright, I'm gonna close this issue

**Comment by spxak1** [comment]
We're on 21.10 and Kooha still doesnt work on Ubuntu and derivatives.

Any updates?

Surely there are others on Ubuntu for whom Kooha doesn't work. Anyone?
