### ISSUE TITLE
[Feature Request] Record to v4l2 loopback

### ISSUE THREAD

**Issue by ngortheone** [SeaDve/Kooha#170]
It would be nice to have an option to record screen and output to v4l2_loopback device. This will enable screen sharing via webcam for applications that don't normally work with Wayland screensharing (Zoom)

**Comment by SeaDve** [comment]
Thanks for reporting!

That would be nice; however, having some output, other than through file, is not aligned with Kooha's current goal. Plus, there would be technical difficulties and more QA testing.

And gladly, the zoom issue seems to be now fixed: I think that issue in Zoom is now fixed: https://github.com/flathub/us.zoom.Zoom/issues/22
