### ISSUE TITLE
Screencast Portal Request Error

### ISSUE THREAD

**Issue by Solarunit** [SeaDve/Kooha#171]
**System Info**
- Kooha version: 2.0.1
- Distro information and version: Solus
- Desktop Environment information and version: Budgie 10.6.2.
- Display Server: X11
- Flatpak: yes

**Describe the bug**

1. After clicking on the Record I see Screen Share window with monitor selection 

![](https://i.imgur.com/nog4WxD.png)

Why do I need a Screen Share?

2. After selecting a monitor and slicking Share I see an error:

![](https://i.imgur.com/xhJyDT6.png)

What is Screencast Portal? Why the app needs it?

**Comment by jsjuris89** [comment]
I have the same error except it happens when I press "record".

- kooha 2.0.1-3
- EndeavourOS
- KDE Plasma 5.25.3
- X11
- [arch repo](https://archlinux.org/packages/community/x86_64/kooha/)

**Comment by kisaragi-hiu** [comment]
> Why do I need a Screen Share?

That window is from the desktop environment. Kooha asks the desktop for the screen, and after you agree, the desktop shares the screen data to Kooha to be recorded.

---

Apart from that, I'm also hitting the same error, both with Kooha installed with Flatpak (from Flathub) and with [the Arch Linux package](https://archlinux.org/packages/community/x86_64/kooha/).

This is the output from the command:

```
$ env RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 kooha
 INFO  kooha::application > Kooha (io.github.seadve.Kooha)
 INFO  kooha::application > Version: 2.0.1 ()
 INFO  kooha::application > Datadir: /usr/share/kooha
 DEBUG kooha::backend::recorder > is_show_pointer: true
 DEBUG kooha::backend::recorder > is_selection_mode: false
 INFO  kooha::backend::screencast_portal > ScreenCastProxy created
 DEBUG kooha::backend::screencast_portal > available_cursor_modes: BitFlags<CursorMode>(0b111, Hidden | Embedded | Metadata)
 DEBUG kooha::backend::screencast_portal > available_source_types: BitFlags<SourceType>(0b11, Monitor | Window)
 ERROR kooha::backend::screencast_portal > Error from screencast call: Response(Other)
```

The error is emitted here:

https://github.com/SeaDve/Kooha/blob/654f8dad17e7703abfbf3b95aaa398c3706bc68e/src/backend/screencast_portal.rs#L81-L97

My system uses X11, and uses PipeWire as the audio server. Perhaps [ashpd::desktop::screencast](https://bilelmoussaoui.github.io/ashpd/ashpd/desktop/screencast/index.html) simply doesn't support this situation?

**Comment by jsjuris89** [comment]
Mine output from terminal:
```
[elnath@elnath-ryzen ~]$ env RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 kooha
 INFO  kooha::application > Kooha (io.github.seadve.Kooha)
 INFO  kooha::application > Version: 2.0.1 ()
 INFO  kooha::application > Datadir: /usr/share/kooha

(kooha:58824): Adwaita-WARNING **: 21:27:48.253: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
 DEBUG kooha::backend::recorder > is_show_pointer: true
 DEBUG kooha::backend::recorder > is_selection_mode: true
 INFO  kooha::backend::screencast_portal > ScreenCastProxy created
 DEBUG kooha::backend::screencast_portal > available_cursor_modes: BitFlags<CursorMode>(0b111, Hidden | Embedded | Metadata)
 DEBUG kooha::backend::screencast_portal > available_source_types: BitFlags<SourceType>(0b11, Monitor | Window)
 ERROR kooha::backend::screencast_portal > Error from screencast call: Response(Other)
[elnath@elnath-ryzen ~]$
```

**Comment by Solarunit** [comment]
> That window is from the desktop environment. Kooha asks the desktop for the screen, and after you agree, the desktop shares the screen data to Kooha to be recorded.

I think it's not very user-friendly, the app should start record immediately like other similar apps e.g. Peek.

**Comment by jsjuris89** [comment]
@SeaDve any solution for this error?

**Comment by SeaDve** [comment]
> > That window is from the desktop environment. Kooha asks the desktop for the screen, and after you agree, the desktop shares the screen data to Kooha to be recorded.
> 
> I think it's not very user-friendly, the app should start record immediately like other similar apps e.g. Peek.

This would be fixed now on the main branch

**Comment by SeaDve** [comment]
Closing this as #129 duplicate for now. Also this [comment](https://github.com/SeaDve/Kooha/issues/129#issuecomment-1060293459) might be helpful

**Comment by Solarunit** [comment]
v2.1.0 Flatpak, the app doesn't work:
after selecting monitor and clicking Share
```
1: Failed to begin ScreencastSession
2: Failed to start screencast session
3: Interaction was ended in some other way with response VariantDict({})
```

**Comment by SeaDve** [comment]
That is likely missing runtime requirements in your host system like GStreamer pipewire

**Comment by CaptainMorgan12** [comment]
> v2.1.0 Flatpak, the app doesn't work: after selecting monitor and clicking Share
> 
> ```
> 1: Failed to begin ScreencastSession
> 2: Failed to start screencast session
> 3: Interaction was ended in some other way with response VariantDict({})
> ```

I have the same error and gstreamer 1.0 and latest version of pipewire are installed.

Environment: kooha flatpak, pureos 10, arm64 mobile, Debian Byzantium, phosh 0.21, kooha 2.2.2, 200% scale, wayland 1.25.

Steps to repeat:

1. install flatpak app,
2. open app,
3. select any screen record function

PS: the copy log does not work and the log details are sparse.

**Comment by Solarunit** [comment]
v2.2.2 Flatpak.
The app don't work for me.

![](https://i.imgur.com/LfqGSim.png)

**Comment by CaptainMorgan12** [comment]
I wonder if this shoukd or could be reopened the suggestions referenced dont really work.

**Comment by Solarunit** [comment]
I think there should be a new issue, because the error is different now. The app never worked for me...
