### ISSUE TITLE
when I want to record, I don't want to start

### ISSUE THREAD

**Issue by dandidwi** [SeaDve/Kooha#172]
-Kooha version 2.0.1
-Distro Fedora 36 Spin Kde Plasma
-Wayland Display Server
-Flatpak

Can't start recording.
You can see in the following video
https://youtube.com/shorts/9uZ8aCDSC9w

**Comment by SeaDve** [comment]
May you show the logs by running Kooha with `flatpak run io.github.seadve.Kooha`?

**Comment by 1011001-p** [comment]
Hey I'm getting the same symptom. When I ran Kooha from the terminal and when I press record I get the following error as a log:
`(kooha:2): Gdk-WARNING **: 17:53:33.320: Server is missing xdg_foreign support`
Hope this helps

**Comment by SeaDve** [comment]
Duplicate of #60
