### ISSUE TITLE
[Feature]H264 and H264 VA-API encoding

### ISSUE THREAD

**Issue by RushingAlien** [SeaDve/Kooha#186]
**System Info**

- io.github.seadve.Kooha 2.1.1
- Flatpak: true

- Distribution: GNOME 42 (Flatpak runtime)
- Desktop Session: gnome
- Display Server: wayland

- GTK 4.6.6
- Libadwaita 1.2.0
- GStreamer 1.18.6

Hello there! AMD hardware has no support for VP8 hardware encoding, so it would be nice to have the option to use vaapih264enc encoder from the gstreamer-vaapi plugin to allow hardware encoding for AMD users.
When I try hardware encoding this happens :
```
Failed to start recording

Caused by:
    0: Sebuah plugin GStreamer mungkin tidak terpasang. Jika itu sudah terpasang namun masih belum bekerja, harap laporkan ke <a href="https://github.com/SeaDve/Kooha/issues">halaman masalah Kooha</a>.
    1: Failed to parse string into pipeline. string: queue name=queue0 ! videorate ! video/x-raw, framerate=30/1 ! videoconvert chroma-mode=GST_VIDEO_CHROMA_MODE_NONE dither=GST_VIDEO_DITHER_NONE matrix-mode=GST_VIDEO_MATRIX_MODE_OUTPUT_ONLY n-threads=8 ! queue ! vaapivp8enc ! queue ! webmmux name=mux ! filesink name=filesink location="/home/raambm/Video/Kooha/Kooha-2022-09-17-20-34-30.webm" pipewiresrc fd=16 path=160 do-timestamp=true keepalive-time=1000 resend-last=true ! video/x-raw ! queue0. pulsesrc device="alsa_output.pci-0000_04_00.6.analog-stereo.monitor" ! opusenc ! queue ! mux.
    2: tak ada elemen "vaapivp8enc"
```

**Comment by SeaDve** [comment]
You can set the format to MP4, to use vaapih264.

However, once 2.1.2 is released, there will be an option to explicitly use specific element for encoding behind a ,`KOOHA_EXPERIMENTAL` env var set to 1.

**Comment by RushingAlien** [comment]
oh okay, thank you
