### ISSUE TITLE
FIrefox and system crashes when recording

### ISSUE THREAD

**Issue by Cherro59** [SeaDve/Kooha#193]
**System Info**
- io.github.seadve.Kooha 2.2.0(2.1.1 too)
- Flatpak: false
- Experimental: false

- Distribution: Fedora Linux 36 (Workstation Edition)
- Desktop Session: gnome
- Display Server: wayland

- GTK 4.6.7
- Libadwaita 1.2.0
- GStreamer 1.20.3
- Pipewire 0.3.58

**To Reproduce**
1. Start screen recording
2. Use firefox
3. Or firefox crashes, or kooha(urecorder), or amdgpu drivers fails

*
**Additional context**
Module linux-vdso.so.1 is crashing after some time on recording. 
I already downgraded the kernel, pipewire,firefox no changes. Downgraded mesa. installed amdgpu still no luck

**Comment by SeaDve** [comment]
Hi, thanks for reporting. Can you show the log with the issue reproduced? Also, is it reproducible in Flatpak?

**Comment by Cherro59** [comment]
Yes it's reproducable in Flatpak. System and apps crashing. Also in logs there is a kernel oops It happens on 5.17 and 5.19. When firefox crash there is no any info in kooha session with debug variables only warns from encoder

**Comment by SeaDve** [comment]
Can I see the version of pipewire in your system? It can be retrieved by running `pipewire --version` in the terminal.

**Comment by Cherro59** [comment]
Pipewire's versions I tried: 0.3.49 and 0.3.58

**Comment by SeaDve** [comment]
That's likely caused by the version mismatch of pipewire and related to #155. So, updating pipeiwre to the latest is likely needed to resolve the issue.
