### ISSUE TITLE
v2.2.2 Crashing on Ubuntu 22.04

### ISSUE THREAD

**Issue by cypherbits** [SeaDve/Kooha#195]
Updated Kooha from 2.1.x to 2.2.2 and I can't record anything. Just closes without any warning/error log if you execute it from flatpak on the terminal.
Updated Ubuntu 22.04 installation. Using Wayland. Pipewire 0.3.48

**Comment by SeaDve** [comment]
Check out the latest comments of #155

**Comment by cypherbits** [comment]
Updated pipewire with official pipewire-debian ppa:

https://launchpad.net/~pipewire-debian/+archive/ubuntu/pipewire-upstream

```
sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream
sudo apt update
```

It is working now. Thanks.

It should put a notice on the Readme.
