### ISSUE TITLE
Screen Recording Crashes with Webm VAAPI VP9

### ISSUE THREAD

**Issue by gianni-rosato** [SeaDve/Kooha#196]
I know it is experimental, but I wanted to share just in case this will help development. Upon attempting to screen record my entire display with WebM VAAPI VP9, Kooha crashes & spits out this error:
`An error occurred while recording

Caused by:
    0: ../libs/gst/base/gstbasesrc.c(3127): gst_base_src_loop (): /GstPipeline:pipeline0/GstBin:bin0/GstPipeWireSrc:pipewiresrc0:
       streaming stopped, reason not-negotiated (-4)
    1: Internal data stream error.`

Is this my fault, or is there something wrong here? I am on Fedora 36.

`➜  ~ inxi
CPU: 12-core (4-mt/8-st) 12th Gen Intel Core i5-1240P (-MST AMCP-)
speed/min/max: 1629/400/4400:3300 MHz Kernel: 5.19.13-200.fc36.x86_64 x86_64
Up: 17h 30m Mem: 4477.1/15704.5 MiB (28.5%) Storage: 476.94 GiB (15.2% used)
Procs: 665 Shell: Zsh inxi: 3.3.21`

Thank you!

**Comment by SeaDve** [comment]
Thanks for reporting! It seems this is a problem with the app. With latest improvements in VA* pipelines, this should be fixed now on the main branch. If not, feel free to reopen the issue.

**Comment by gianni-rosato** [comment]
Thanks for checking on this issue over a year later! The dedication is admirable - I'll be giving Kooha's hardware acceleration another look!
