### ISSUE TITLE
Add support for recording a specific monitor

### ISSUE THREAD

**Issue by lifeiscontent** [SeaDve/Kooha#198]
I'm currently using dual monitors and would like the ability to record a specific one rather than both (current behavior)

**Comment by SeaDve** [comment]
That is currently supported since 2.0.0 afair.

**Comment by lifeiscontent** [comment]
@SeaDve thanks for your prompt response. I see flatpak is reporting the version 2.2.2 is installed but in the about section of the app I see 1.2.1

![image](https://user-images.githubusercontent.com/180963/195896136-1827632c-4799-4929-98fd-7333eeb7210d.png)
![image](https://user-images.githubusercontent.com/180963/195896058-c3be0cb6-35fd-4c4a-87a6-c0df6f0a3a9a.png)

**Comment by SeaDve** [comment]
Then, you need to update it.

**Comment by lifeiscontent** [comment]
@SeaDve sorry, maybe I didn't express what I was trying to articulate correctly.

there is no update. The Gnome Software app says I have version 2.2.2 installed, but when I actually run the app it reports I'm running 1.2.1

**Comment by SeaDve** [comment]
Ah, no worries.

Did you install it from Flatpak, AUR, apt, etc.?

**Comment by lifeiscontent** [comment]
hmm I've managed to get version 2.2.2 installed but now when I try to record my screen I get the following error:

```
Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x7f5a4c002290, type: VariantTy { inner: "(a{sv})" }, value: "({'handle_token': <'kooha_1'>, 'session_handle_token': <'kooha_0'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
```

installed via FlatHub, running Zorin OS 16 (basically Ubuntu 20.04)
