### ISSUE TITLE
Forever stuck in "Flushing" until cancelled

### ISSUE THREAD

**Issue by mystrdat** [SeaDve/Kooha#201]
**System Info**
io.github.seadve.Kooha 2.2.2
Flatpak: true
Experimental: false

Distribution: GNOME 43 (Flatpak runtime)
Desktop Session: gnome
Display Server: wayland

GTK 4.8.1
Libadwaita 1.2.0
GStreamer 1.20.3
Pipewire 0.3.57

**Describe the bug**
When video recording is stopped, the app is forever stuck in the "Flushing" dialog with some disk activity around the video file. When cancelled, the file is deleted. The file is never completed correctly and is damaged.

**To Reproduce**
Just start recording.

**Expected behavior**
Should, um, record.

**Additional context**
This is the log after starting the recording and then cancelling it because it never finishes.
```
2022-10-20T13:49:58.075179Z DEBUG kooha::recording: Pipeline changed state from `Paused` -> `Playing`
2022-10-20T13:50:02.489243Z DEBUG kooha::recording: Sending eos event to pipeline
2022-10-20T13:50:21.456422Z DEBUG kooha::recording: Cancelling recording
0:00:30.901585560     2 0x7fb49c0cad20 WARN                audiosrc gstaudiosrc.c:227:audioringbuffer_thread_func:<pulsesrc0> error reading data -1 (reason: Success), skipping segment
[I][20494.605920] pw.stream    | [        stream.c:  587 impl_send_command()] 0x562fd9b66720: command Spa:Pod:Object:Command:Node:Pause
[I][20494.605979] pw.node      | [     impl-node.c:  379 node_update_state()] (kooha-0) running -> idle
[I][20494.609904] pw.stream    | [        stream.c:  587 impl_send_command()] 0x562fd9b66720: command Spa:Pod:Object:Command:Node:Suspend
[I][20494.609926] pw.node      | [     impl-node.c:  379 node_update_state()] (kooha-0) idle -> suspended
[I][20494.609956] pw.node      | [     impl-node.c: 1814 pw_impl_node_destroy()] (kooha-0) destroy
2022-10-20T13:50:21.462566Z DEBUG kooha::window: Cancelled recording
0:00:30.907501646     2 0x562fd87b5690 ERROR                GST_BUS gstbus.c:1075:gst_bus_remove_watch:<bus9> no bus watch was present
2022-10-20T13:50:21.480429Z DEBUG kooha::screencast_session: Closed screencast session response=()
```

**Comment by LukeZBaker** [comment]
I got the same issue. 

If Desktop Audio and Microphone are disabled, recording works. If either are enabled, the app is forever stuck in the "Flushing" dialog.

- io.github.seadve.Kooha 2.2.2
- Flatpak: true
- Experimental: false

- Distribution: GNOME 43 (Flatpak runtime)
- Desktop Session: ubuntu
- Display Server: x11

- GTK 4.8.2
- Libadwaita 1.2.0
- GStreamer 1.20.3
- Pipewire 0.3.57

**Comment by fasi747** [comment]
I have the exact issue, I am using Fedora 37 beta.

**Comment by sallyahaj** [comment]
Same issue here on Fedora 37 using Raspberry Pi 4. 
Installed it from flathub

**Comment by iamaakashbasnet** [comment]
Any updates?

**Comment by virgiliovasconcelos** [comment]
I have the same issue, using Debian GNU/Linux bookworm/sid x86_64, GNOME 43.0, flatpak, wayland.

FYI: after downgrading it to version 2.2.1 that issue was gone, so it's probably specific to 2.2.2

**Comment by UnsuitableFollower** [comment]
Still working here but VERY Slow flushing.
(Fedora 37 beta)

**Comment by JumpLink** [comment]
Same here using Fedora 37

**Comment by knuxify** [comment]
Similar yet different issue here, on Alpine Linux edge, with Kooha 2.2.2; however, instead of the errors posted here, there's a different error message:

```
(kooha:20085): GStreamer-CRITICAL **: 21:18:39.588: gst_mini_object_unlock: assertion 'state >= SHARE_ONE' failed
```

This is printed a few times when recording is started, and hundreds of times per second when flushing. Similar failure mode as presented here though - recording with desktop audio off works fine, enabling it causes issues. Changing the filetype doesn't fix it.

System information:

```
- io.github.seadve.Kooha 2.2.2
- Flatpak: false
- Experimental: false

- Distribution: Alpine Linux v3.17
- Desktop Session: gnome
- Display Server: wayland

- GTK 4.8.2
- Libadwaita 1.2.0
- GStreamer 1.20.4
- Pipewire 0.3.60
```

**Comment by kristofgilicze** [comment]
Same happened to me, it was a fresh install so likely less people are effected.

To reproduce the issue on my system I can do the following:

0. uninstall current kooha
2. install kooha
3. observe issue with flushing (2.2.2)
4. downgrade to 2.2.1
5. works on 2.2.1
6. upgrade to latest (2.2.2)
7. now it does work with 2.2.2 :)

_I'm not familiar with flatpak, but it seems maybe some sort of dependency / cfg is missing from the new build._

**Comment by darkblaze69** [comment]
The same issue with native app v2.2.2 (without flatpak) on Manjaro GNOME. Stuck "flushing". But if disable sound it flushes at once without problems. So the problem's in sound stack.

**Comment by knuxify** [comment]
Could somebody test if the patch in #209 fixes the issue? It seems to work for me. It's a partial revert of a change made in a86fb9430ef01977497ca5acde4a30f7ddf9189c, between 2.2.1 and 2.2.2, which also matches what other people have been reporting.

**Comment by gnunn1** [comment]
I tested that PR (adding that one line back in), built Kooha and it fixed the flushing issue for me, I don't get any audio recorded (no default device) but I'll track that down and open a separate issue for it.

**Comment by Poly2it** [comment]
I am experiencing the same issue on Ubuntu 22.10.

**Comment by Ezema** [comment]
that worked @knuxify thanks :smile:

**Comment by Serkan80** [comment]
> I have the same issue, using Debian GNU/Linux bookworm/sid x86_64, GNOME 43.0, flatpak, wayland.
> 
> FYI: after downgrading it to version 2.2.1 that issue was gone, so it's probably specific to 2.2.2

I can also confirm that after downgrading to version 2.2.1 from 2.2.4  it works.

**Comment by cccaballero** [comment]
I'm using Kooha 2.2.4 (flatpack) in Ubuntu 22.04 and wayland, and I'm having the same (or similar) issue. The app is stuck in the "Flushing" dialog, looks like it's doing something, but really slow, or in some kind of loop.

Logs:

> 2023-11-01T23:33:00.971179Z  INFO kooha::application: Kooha (io.github.seadve.Kooha)
2023-11-01T23:33:00.971190Z  INFO kooha::application: Version: 2.2.4 ()
2023-11-01T23:33:00.971191Z  INFO kooha::application: Datadir: /app/share/kooha
2023-11-01T23:33:05.631632Z  WARN kooha::audio_device: Skipping device `pulsedevice5` as it has no node.name property. FieldNotFound { name: "node.name" }
2023-11-01T23:33:05.631690Z  WARN kooha::audio_device: Failed to find default name using gstreamer: Failed to find a default device
2023-11-01T23:33:05.635932Z  WARN kooha::audio_device: Skipping device `pulsedevice23` as it has no node.name property. FieldNotFound { name: "node.name" }
2023-11-01T23:33:05.635980Z  WARN kooha::audio_device: Failed to find default name using gstreamer: Failed to find a default device

**Comment by uyriq** [comment]
I installed Kooha flatpack a week ago and everything worked fine at first, but now I have the same problem as above in the track. 
I think it might depend on something ubuntu did in the update. unfortunately I don't know what logs to collect. 
Now if I run
``bash
➜ flatpak run io.github.seadve.Kooha 
2024-01-15T17:05:17.385255Z INFO kooha::application: Kooha (io.github.seadve.Kooha)
2024-01-15T17:05:17.385271Z INFO kooha::application: Version: 2.2.4 ()
2024-01-15T17:05:17.385275Z INFO kooha::application: Datadir: /app/share/kooha
2024-01-15T17:05:35.907442Z WARN kooha::audio_device: Skipping device `pulsedevice1` as it has no node.name property. FieldNotFound { name: "node.name" }
2024-01-15T17:05:35.907521Z WARN kooha::audio_device: Failed to find default name using gstreamer: Failed to find a default device
2024-01-15T17:05:35.914717Z WARN kooha::audio_device: Skipping device `pulsedevice17` as it has no node.name property. FieldNotFound { name: "node.name" }
2024-01-15T17:05:35.914781Z WARN kooha::audio_device: Failed to find default name using gstreamer: Failed to find a default device
![Screenshot from 2024-01-15 18-11-02](https://github.com/SeaDve/Kooha/assets/105006434/99765828-725e-4195-b613-9213f39cfc7e)

```

**Comment by antonioaltamura** [comment]
how this has been closed as this is still an issue?

**Comment by SeaDve** [comment]
There's a new open issue about it: https://github.com/SeaDve/Kooha/issues/105
