### ISSUE TITLE
[Feature] Capture a program and its audio

### ISSUE THREAD

**Issue by GreenLunar** [SeaDve/Kooha#211]
~~Cature a specific program.~~

~~User may select a program from menu (of active programs) or select an active program.~~

~~Kooha will~~

Record selected program and its audio.
Only the audio source of the program.
Ignore all other audio streams of other sources.

~~Preferably, if feasible, Kooha will lock the window size and location of the selected program and will also lock placement on top of all windows.~~

~~I'm not sure about it though.~~
~~Sound complicated.~~

~~What do you think?~~

**Comment by SeaDve** [comment]
This is unfortunately not practically possible with current desktop APIs. Closing this for now since it is not realistically attainable any time soon.

However, there is an open issue at https://github.com/flatpak/xdg-desktop-portal/issues/957
