### ISSUE TITLE
Unable to capture fullscreen apps

### ISSUE THREAD

**Issue by abc-mikey** [SeaDve/Kooha#214]
**System Info**
- io.github.seadve.Kooha 2.2.3
- Flatpak: true
- Experimental: false

- Distribution: GNOME 43 (Flatpak runtime)
- Desktop Session: gnome
- Display Server: wayland

- GTK 4.8.3
- Libadwaita 1.2.0
- GStreamer 1.20.4
- Pipewire 0.3.59

**Describe the bug**
Running a application/game in fullscreen fails to capture.

See screenshot: 

**To Reproduce**
1. Start recording 
2. Launch application / game with output mode "fullscreen"
3. Stop recording
4. Watch checkerboard pattern in video

**Expected behavior**
Capture fullscreen output to video.

**Screenshots**
![Screenshot from 2023-01-07 00-28-07](https://user-images.githubusercontent.com/2983924/211116536-43fab88e-d4ae-431a-a1f2-77dadfb1175f.png)

**Additional context**
[Kooha.log](https://github.com/SeaDve/Kooha/files/10364160/Kooha.log)

**Comment by abc-mikey** [comment]
This looks to likely be the error:

```
0:00:25.896706428     2 0x7f62e80f0920 ERROR                default video-frame.c:181:gst_video_frame_map_id: invalid buffer size 0 < 33177600
0:00:25.896741609     2 0x7f62e80f0920 WARN         videoaggregator gstvideoaggregator.c:829:gst_video_aggregator_parallel_convert_pad_prepare_frame_start:<compositor0> Could not map input buffer
```

**Comment by abc-mikey** [comment]
Is this the correct place to report this? Is it an issue with using portals `org.freedesktop.portal.ScreenCast` for screen-capture? Should I maybe report it somewhere upstream?

**Comment by SeaDve** [comment]
Thanks for the bug issue. Closing this in favor of https://github.com/SeaDve/Kooha/issues/270
