### ISSUE TITLE
Failed to start recording

### ISSUE THREAD

**Issue by PouyaPouryaie** [SeaDve/Kooha#215]
**System Info**

**Describe the bug**
Failed to start recording when click on record button

**To Reproduce**
1. Go to 'kooha'
2. Click on 'Record'
3. See error

**Additional context**
Caused by:
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x7f43f0003000, type: VariantTy { inner: "(a{sv})" }, value: "({'handle_token': <'kooha_1'>, 'session_handle_token': <'kooha_0'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop.

**Comment by dongdongbh** [comment]
same error with
```
distro: ubuntu server 20.04
wm: bspwm
display: X
```

**Comment by AlexDaniel** [comment]
Same error but on Sway.

**Comment by dongdongbh** [comment]
I just switch to simplescreenrecorder, it works fine on my machine.

**Comment by AlexDaniel** [comment]
Actually, based on [that comment](https://github.com/hyprwm/Hyprland/issues/276#issuecomment-1170494920), I just had to kill and restart both xdg-desktop-portal and xdg-desktop-portal-wlr. After that Kooha manages to attempt to start recording but fails with:

> Failed to find element factory with name 'pipewiresrc' for creating element

**Comment by KaKi87** [comment]
Hello,

I'm experiencing the same issue on Ubuntu Unity 22.04, any news on this @SeaDve ?

Thanks
