### ISSUE TITLE
ninja build error

### ISSUE THREAD

**Issue by jbhntr861** [SeaDve/Kooha#216]
when building from gh repo clone SeaDve/Kooha

install dependencies
(install beta rustup)

sudo meson setup build

cd install

sudo ninja
ninja: error: '/usr/bin/cargo', needed by 'src/kooha', missing and no known rule to make it 

im stumped here clearly not a Kooha bug but does anyone know what I'm supposed to do here?

**Comment by SeaDve** [comment]
You need to have cargo installed via `rustup` etc.
