### ISSUE TITLE
Without support to record windows

### ISSUE THREAD

**Issue by dinhokusanagi** [SeaDve/Kooha#222]
Fedora Silverblue 37
Kooha -> Flatpak

2023-02-02T12:34:39.420229Z  INFO kooha::application: Kooha (io.github.seadve.Kooha)
2023-02-02T12:34:39.420250Z  INFO kooha::application: Version: 2.2.3 ()
2023-02-02T12:34:39.420254Z  INFO kooha::application: Datadir: /app/share/kooha

The OBS Studio application works normally in any application already in Kooha no longer supports

![Captura de tela de 2023-02-02 09-30-55](https://user-images.githubusercontent.com/43162113/216326698-a6a88dd7-139d-494d-b441-ae02fb9d029a.png)
![Captura de tela de 2023-02-02 09-32-09](https://user-images.githubusercontent.com/43162113/216326704-a1478446-572d-4eca-bdb8-ee167aabdb93.png)

**Comment by hendursaga** [comment]
Did you enable experimental features? https://github.com/SeaDve/Kooha#recording-specific-window

**Comment by SeaDve** [comment]
This is supported, see https://github.com/SeaDve/Kooha#recording-specific-window like `hendursaga` said.
