### ISSUE TITLE
no codec available

### ISSUE THREAD

**Issue by ddams2000** [SeaDve/Kooha#225]
**System Info**

Operating System: Manjaro ARM 
KDE Plasma Version: 5.27.1
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.2.1-1-MANJARO-ARM (64-bit)
Graphics Platform: Wayland
Processors: 2 × ARM Cortex-A53, 4 × ARM Cortex-A73
Memory: 3.6 Gio of RAM
Graphics Processor: Mali-G52
Product Name: Ugoos AM6b Plus

**Describe the bug**

no codec available

**Screenshots**
![Screenshot_20230227_103831](https://user-images.githubusercontent.com/101818343/221528297-7581750b-5774-4361-bf8f-fbf83f5b94fe.png)
now it stayed on gif, but anyway I only had this choice...

**Additional context**
If applicable, please attach the logs from running Kooha in the
terminal with the following environment variables: `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3`
(e.g., `RUST_BACKTRACE=1 RUST_LOG=kooha=debug GST_DEBUG=3 PIPEWIRE_DEBUG=3 flatpak run io.github.seadve.Kooha`).

**Comment by friedrich-de** [comment]
Same issue on EndeavourOS KDE/Wayland. Running with the debug command revealed the following issue:

```
2023-03-16T22:06:05.678349Z  WARN kooha::element_properties: Failed to set property keyframe-mode to disabled: Factory vp8enc not found
2023-03-16T22:06:05.678451Z DEBUG kooha::profile: Profile webm is unavailable. Caused by: Factory webmmux not found
2023-03-16T22:06:05.679193Z DEBUG kooha::profile: Profile mp4 is unavailable. Caused by: Factory mp4mux not found
2023-03-16T22:06:05.679255Z DEBUG kooha::profile: Profile matroska is unavailable. Caused by: Factory matroskamux not found
```

In other words: missing gstreamer plugins/runtime dependencies. This was fixed by installing the `gst-plugins-good` package. Not sure if it's an issue specific to arch-based distributions but a mention in the README might help.

**Comment by ddams2000** [comment]
> Same issue on EndeavourOS KDE/Wayland. Running with the debug command revealed the following issue:
> 
> ```
> 2023-03-16T22:06:05.678349Z  WARN kooha::element_properties: Failed to set property keyframe-mode to disabled: Factory vp8enc not found
> 2023-03-16T22:06:05.678451Z DEBUG kooha::profile: Profile webm is unavailable. Caused by: Factory webmmux not found
> 2023-03-16T22:06:05.679193Z DEBUG kooha::profile: Profile mp4 is unavailable. Caused by: Factory mp4mux not found
> 2023-03-16T22:06:05.679255Z DEBUG kooha::profile: Profile matroska is unavailable. Caused by: Factory matroskamux not found
> ```
> 
> In other words: missing gstreamer plugins/runtime dependencies. This was fixed by installing the `gst-plugins-good` package. Not sure if it's an issue specific to arch-based distributions but a mention in the README might help.

Thanks for the tip, now I have access to several codecs unfortunately the app crashes the whole system when I launch a capture :(

**Comment by SeaDve** [comment]
Thanks for reporting! Since I think there is nothing we can do from the app side, I am closing this.
