### ISSUE TITLE
weblate: closed for contributions due to "Could not push the repository."

### ISSUE THREAD

**Issue by rffontenelle** [SeaDve/Kooha#23]
Translations for Kooha in Weblate are currently closed because Weblate failed to push contributions to the upstream repository (this one), which can be verified in the alerts page: https://hosted.weblate.org/projects/kooha/pot-file/#alerts

Can you please verify the setup? I'd suggest checking whether the `weblate` user in GitHub has sufficient permissions on this repository. Alternatively, see [Translation projects in Weblate Docs](https://docs.weblate.org/en/latest/admin/projects.html).

![Captura de tela de 2021-03-17 08-09-20](https://user-images.githubusercontent.com/1571783/111458381-1c50c980-86f8-11eb-8cec-cebb5e6e9d17.png)

**Comment by SeaDve** [comment]
I should've read the docs first, I randomly enter random strings hehe. I'll get back to this soon.

**Comment by SeaDve** [comment]
I would say weblate documentations seems incomplete. You have to look for other resources to understand it...

**Comment by rffontenelle** [comment]
As a translator of the weblate documentation, I'd say it is sooo big that would amaze not being complete.

Just kidding...  Sadly I never set up a project to have an opinion on this topic. If you have any question, feel free to bring it here and I use my google-fu and readthedocs-search-fu to help.

**Comment by SeaDve** [comment]
That must be it, the documentation is too big, I can't find what I am looking for, lol. Kidding aside, I think weblate website is now unlocked. The only problem is I'm not sure how to push the changes here to this branch.

**Comment by rffontenelle** [comment]
Have you configured pushes to GitHub to either one of directly or pull requests (your choice) as documented in https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate ?

**Comment by SeaDve** [comment]
https://docs.weblate.org/en/latest/vcs.html#vcs-github
There's this part wherein `You need to configure API credentials to make this work.` but there are no instructions on how to configure API credentials.

**Comment by rffontenelle** [comment]
This [Configuration](https://docs.weblate.org/en/latest/admin/config.html) page seems to be targeting those with self-hosted Weblate, as those configs should set in `settings.py`. This doesn't concern using Hosted Weblate.

Consider reading [Continuous](https://docs.weblate.org/en/latest/admin/continuous.html) page from the top ending yhe reading with section "Automatically receiving changes from GitHub" (not too much text).

**Comment by SeaDve** [comment]
I already set up that section including the webhooks, etc. However, I think that is only for getting the .pot file changes. Not the other way around.

**Comment by rffontenelle** [comment]
How about [repository push URL](https://docs.weblate.org/en/latest/admin/projects.html#repository-push-url)? Its "see also" links to "Accessing repositories" section in [VCS](https://docs.weblate.org/en/latest/vcs.html#vcs-repos) page.

**Comment by SeaDve** [comment]
Repository push URL seems not to be needed according to [this](https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes-from-weblate), I'm good with pushing translation from fork, not directly from a branch.

**Comment by SeaDve** [comment]
NVM, I just gave write access to weblate, lol. Going with the nuclear option. Gonna close this now, thanks!

**Comment by rffontenelle** [comment]
Awesome, thanks
