### ISSUE TITLE
config to disable checkbox "remember this selection"

### ISSUE THREAD

**Issue by VeldoraTheDragon** [SeaDve/Kooha#232]
Currently, the checkbox of "remember my selection" is checked by default, when starting to record my screen.
Is there a way to configure the checkbox, for it to be disabled by default?

It's quite annoying, and sometimes I want to record a different screen, as I have a multi-monitor setup.
When keeping it checked by accident, kooha always records the same monitor and I don't have an option to change it.

Thanks
~Veldora

**Comment by VeldoraTheDragon** [comment]
Managed to set default configs in user.txt

**Comment by 103sbavert** [comment]
Can you tell me which dconf key you used for this? @VeldoraTheDragon

**Comment by VeldoraTheDragon** [comment]
@103sbavert 
Then I used `screencast-restore-token=''` within the dconf settings:
```
[io/github/seadve/Kooha]
screencast-restore-token=''
```

However according to my todays tests, it seems to not be working anymore. :(
There will however be an additional button next to `Record` if you set the default recording device. 
This button will reset it again.
