### ISSUE TITLE
Crashes thread 'main' panicked at 'assertion failed:

### ISSUE THREAD

**Issue by rickalex21** [SeaDve/Kooha#234]
**System Info**

Thre is no Main Menu Troubleshooting > Debugging

**Describe the bug**

```sh
thread 'main' panicked at 'assertion failed: !ptr.is_null()', /builddir/Kooha-2.0.1/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.14.5/src/gstring.rs:62:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
**To Reproduce**

open kooha from a terminal try to capture a video and it crashes.

**Expected behavior**

For it to work.

**Screenshots**

I need this program to create a gif for another issue.

**Additional context**
Running Void Linux Wayland with River
Linux void 6.1.14_1 #1 SMP PREEMPT_DYNAMIC Mon Feb 27 15:21:49 UTC 2023 x86_64 GNU/Linux

**Comment by SeaDve** [comment]
This issue is fixed on the latest versions btw

**Comment by SeaDve** [comment]
Closed as fixed.
