### ISSUE TITLE
Recording also records "Tong" (start recording sound)

### ISSUE THREAD

**Issue by fastrizwaan** [SeaDve/Kooha#24]
Please unmute and we can hear "Ting" / "Tong" / "beep" sound  at the start of video

I've recorded with selection.

https://user-images.githubusercontent.com/1161682/111568413-b717d980-87c6-11eb-8bdc-877d2de5a179.mp4

https://user-images.githubusercontent.com/1161682/111568558-fba37500-87c6-11eb-8cee-6f51703f67ed.mp4

https://user-images.githubusercontent.com/1161682/111568675-2b527d00-87c7-11eb-9029-352443873477.mp4

**Comment by SeaDve** [comment]
I think this isn't a serious issue, so I'll label this as enhancement. But this issue should be fixed in v2.0.0, since at the present, it uses that sound to signal GStreamer to, hey, start recording sounds. If there is no signal, it will make the audio unsynced with the video. In 2.0.0, I'll merge video and audio to one stream, improving performance and fixing this issue.

**Comment by fastrizwaan** [comment]
perhaps you can signal gstreamer with "blank" / "silent" / empty audio stream.

**Comment by SeaDve** [comment]
> perhaps you can signal gstreamer with "blank" / "silent" / empty audio stream.

Not sure how, can you reference some?

**Comment by fastrizwaan** [comment]
https://github.com/anars/blank-audio/raw/master/2-seconds-and-500-milliseconds-of-silence.mp3

**Comment by fastrizwaan** [comment]
https://github.com/anars/blank-audio/blob/master/1-second-of-silence.mp3

**Comment by SeaDve** [comment]
I'll look on how to implement these, thanks!

**Comment by fastrizwaan** [comment]
> it uses that sound to signal GStreamer to, hey, start recording sounds. If there is no signal, it will make the audio unsynced with the video.
instead of audible sound, please use this 1-second-of-silence.mp3 https://github.com/anars/blank-audio/raw/master/1-second-of-silence.mp3

**Comment by fastrizwaan** [comment]
hi, got it working by replacing chime.ogg with converted 1-second-of-silence.mp3
`ffmpeg -i ~/Downloads/1-second-of-silence.mp3 -vn ~/Kooha/data/sounds/chime.ogg`

then build and install, no chime and audio is recording

```
meson builddir --prefix=/usr/local
ninja -C builddir install
```

Here's another clip which has no tong/chime

https://user-images.githubusercontent.com/1161682/111960649-fff8c680-8b15-11eb-8e67-e1b1a0a4a425.mp4

**Comment by SeaDve** [comment]
Thanks! I already pushed it to flatpak and will soon release it together with 1.0.4 in flathub.
