### ISSUE TITLE
Improve speed of flushing

### ISSUE THREAD

**Issue by soo-shan** [SeaDve/Kooha#244]
I used kooha for record an hour of screen with audio. Its been more than 24 hours and the app is still flushing the video. The size of recorded video is slowly increasing (currently around 815.2 MB).

Is there a way to speed up flushing ? 

System Details: 
`inxi -B`
`System:
  Host: fedora Kernel: 6.2.15-200.fc37.x86_64 arch: x86_64 bits: 64
    Desktop: GNOME v: 43.5 Distro: Fedora release 37 (Thirty Seven)
Machine:
  Type: Laptop System: Hewlett-Packard product: HP Notebook
    v: Type1ProductConfigId serial: <superuser required>
  Mobo: Hewlett-Packard model: 80C2 v: 96.51 serial: <superuser required>
    UEFI: Insyde v: F.27 date: 07/05/2018
Battery:
  ID-1: BAT1 charge: 27.0 Wh (95.4%) condition: 28.3/32.6 Wh (86.9%)
CPU:
  Info: dual core Intel Core i5-5200U [MT MCP] speed (MHz): avg: 2523
    min/max: 500/2700
Graphics:
  Device-1: Intel HD Graphics 5500 driver: i915 v: kernel
  Device-2: AMD Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 M430 Radeon
    520 Mobile] driver: amdgpu v: kernel
  Device-3: Suyin HP Truevision HD type: USB driver: uvcvideo
  Display: wayland server: X.Org v: 22.1.9 with: Xwayland v: 22.1.9
    compositor: gnome-shell driver: dri: iris gpu: i915
    resolution: 1366x768~60Hz
  API: OpenGL v: 4.6 Mesa 23.0.3 renderer: Mesa Intel HD Graphics 5500 (BDW
    GT2)
Network:
  Device-1: Realtek RTL810xE PCI Express Fast Ethernet driver: r8169
  Device-2: Broadcom BCM43142 802.11b/g/n driver: N/A
  Device-3: TP-Link 802.11ac WLAN Adapter type: USB driver: rtl88XXau
Drives:
  Local Storage: total: 689.34 GiB used: 139.62 GiB (20.3%)
Info:
  Processes: 310 Uptime: 1d 4h 48m Memory: 7.66 GiB used: 5.54 GiB (72.3%)
  Shell: Bash inxi: 3.3.26
`

Update:
After 48 hours, file size is around 1.4 GB and still flushing

Found same mentioned in another issue: https://github.com/SeaDve/Kooha/issues/105#issuecomment-1413603795

**Comment by Delta456** [comment]
Facing the same issue

**Comment by BobDodds** [comment]
Kooha 2.2.4, flatpak, Ubuntu 23.10. 2 gig file, from 1 hour video, after a few minutes, but no change in 12 hours. Maximizing from dock, kooha box says Flushing...hours and hours. Properties of file, no playable streams. Try to load in Video, no playable streams error message. Is it really flushing? Set to output mp4. Should try a 3 minute video.

**Comment by SeaDve** [comment]
Thanks for reporting and sorry for the issue. I am gonna close this in favor of https://github.com/SeaDve/Kooha/issues/105
