### ISSUE TITLE
Can't Screen Recording

### ISSUE THREAD

**Issue by Kerberonos** [SeaDve/Kooha#248]
**System Info**
My OS :  Parrot OS
App : Kooha 2.2.3

**Describe the bug**
Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Interaction was ended in some other way with response Variant { ptr: 0x55da70d4b3a0, type: VariantTy { inner: "a{sv}" }, value: "@a{sv} {}" }

**To Reproduce**
1. Open Kooha
2. I just click on both screen recorder icon
3. then i see error

**Screenshots**
![tanya_ke_Kooha](https://github.com/SeaDve/Kooha/assets/99790148/361e0352-67bb-4320-b2df-3c178b262f53)

.

**Comment by SeaDve** [comment]
Thanks for the bug issue. This particular issue has already been reported in https://github.com/SeaDve/Kooha/issues/202, so this report is being marked as a duplicate.
