### ISSUE TITLE
Unable to select multiple monitors

### ISSUE THREAD

**Issue by ianhattendorf** [SeaDve/Kooha#249]
**Affected version**

Sway 1.8.1

- io.github.seadve.Kooha 2.2.3
- Flatpak: true
- Experimental: false

- Distribution: GNOME 44 (Flatpak runtime)
- Desktop Session: <unknown>
- Display Server: wayland

- GTK 4.10.4
- Libadwaita 1.3.3
- GStreamer 1.20.6
- Pipewire 0.3.69

**Bug summary**

Kooha only records to one monitor, with no option to select one of the other two monitors. Selecting monitor or window immediately starts recording one of the monitors, selecting selection of screen displays the selection of a single monitor (the monitor is also rotated, see #250).

**Steps to reproduce**

1. Open Kooha
2. Try to record to monitor or selection
3. No option to select which monitor

**Expected behavior**

Option to select monitor to record on

**Relevant logs, screenshots, screencasts, etc.**

![image](https://github.com/SeaDve/Kooha/assets/2917725/df1c2444-7c0f-48fd-8d9a-9d779ba43b5f)

[kooha.log](https://github.com/SeaDve/Kooha/files/12245387/kooha.log)

**Comment by ianhattendorf** [comment]
If this is an upstream issue (flatpak, xdg-desktop-portal-wlr, wlroots,etc.) please redirect me. Thanks!

**Comment by nerumo** [comment]
I'm having this problem on a KDE environment. Is this a problem in this project or in xdg-desktop-portal-kde?

**Comment by alichtman** [comment]
I'm having this problem on Ubuntu 23.10, running GNOME.

**Comment by SeaDve** [comment]
This should be possible now on the latest version. Please feel free to reopen if it is still reproducible, thanks!
