### ISSUE TITLE
MP4 format?

### ISSUE THREAD

**Issue by fastrizwaan** [SeaDve/Kooha#25]
MP4 is more popular, please consider adding MP4 container.

I've recorded screen to mkv file, then renamed the file to MP4 to upload it here.

This is actually mkv file renamed to .mp4 for github.

https://user-images.githubusercontent.com/1161682/111568790-62c12980-87c7-11eb-8d61-bb62d09b8647.mp4

**Comment by SeaDve** [comment]
Mp4 should come in 2.0.0 too

**Comment by SeaDve** [comment]
#65 working on it

**Comment by SeaDve** [comment]
merged to main

**Comment by fmendezy** [comment]
On Ubuntu 24.04 the format .mp4 not found.

![Image](https://github.com/user-attachments/assets/82ea092b-0ab8-4497-a126-9f8bf9b300fa)

**Comment by matthias-ccri** [comment]
Installed from snap -- no mp4

**Comment by fmendezy** [comment]
Work now! **in flatpak versión**:
`flatpak install flathub io.github.seadve.Kooha -y`

for run:
`flatpak run io.github.seadve.Kooha`


![Image](https://github.com/user-attachments/assets/90a69ada-e56d-4173-9dee-6af763752b4b)
