### ISSUE TITLE
Kooha monitor rotated

### ISSUE THREAD

**Issue by ianhattendorf** [SeaDve/Kooha#250]
**Affected version**

Sway 1.8.1

- io.github.seadve.Kooha 2.2.3
- Flatpak: true
- Experimental: false

- Distribution: GNOME 44 (Flatpak runtime)
- Desktop Session: <unknown>
- Display Server: wayland

- GTK 4.10.4
- Libadwaita 1.3.3
- GStreamer 1.20.6
- Pipewire 0.3.69

**Bug summary**

A rotated monitor is recorded as rotated. It would be nice to have some sort of control over this, as typically monitors are rotated so that they are still viewed normally. A monitor moved into portrait mode would be rotated in software 90 or 270 degrees, but I would expect to be able to record right side up.

In this case, to fix the recording I need to re-encode the video via `ffmpeg -i <video> -vf 'transpose=1' <out>`. This isn't ideal as it's slow, kills battery, and loses quality.

**Steps to reproduce**

1. Open Kooha
2. Record on rotated monitor
3. Recording is rotated

**Expected behavior**

Recording is not rotated

**Relevant logs, screenshots, screencasts, etc.**

![image](https://github.com/SeaDve/Kooha/assets/2917725/df1c2444-7c0f-48fd-8d9a-9d779ba43b5f)

**Comment by ianhattendorf** [comment]
If this is an upstream issue (flatpak, xdg-desktop-portal-wlr, wlroots,etc.) please redirect me. Thanks!

**Comment by SeaDve** [comment]
I think this may be a bug in your compositor

**Comment by SeaDve** [comment]
Thanks for reporting btw. However, I'll close this for now since I don't think we can do much from Kooha's side. Feel free to reopen though if otherwise it is.

**Comment by SeaDve** [comment]
Hello, I have pushed a fix in the main branch. If you have the time, please test it. Thank youu!

**Comment by ianhattendorf** [comment]
> Hello, I have pushed a fix in the main branch. If you have the time, please test it. Thank youu!

Sorry, missed that this was resolved. I don't have a rotated monitor anymore, but a quick test confirms that it's fixed. Thanks!
