### ISSUE TITLE
It doesn't record

### ISSUE THREAD

**Issue by PSGitHubUser1** [SeaDve/Kooha#259]
**Affected version**
GNOME 44.1, Kooha 2.2.4 

**Bug summary**
```error
Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x561c8a6381b0, type: VariantTy { inner: "(a{sv})" }, value: "({'handle_token': <'kooha_1'>, 'session_handle_token': <'kooha_0'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
```

**Steps to reproduce**

**Expected behavior**

**Relevant logs, screenshots, screencasts, etc.**

**Comment by SeaDve** [comment]
Your DE's portal implementation doesn't seem to support the ScreenCast portal

**Comment by PSGitHubUser1** [comment]
I'm using Kali Linux with GNOME

**Comment by sstefanofm** [comment]
Hello @PSGitHubUser1 
I think the problem may be that you don't have [xdg-desktop-portal-gnome](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/) backend installed.
Probably `sudo apt install xdg-desktop-portal-gnome` should fix it.

**Comment by JwanKhalaf** [comment]
What about if one is using bspwm & polybar. Would kooha work with that, @sstefanofm?
