### ISSUE TITLE
Select Area window is tiny and not resizable

### ISSUE THREAD

**Issue by kidonng** [SeaDve/Kooha#260]
**Affected version**

Kooha 2.2.4
With KDE 5.27.9 (using 150% scale on Wayland; stock config, not using any themes) on Arch Linux

**Bug summary**

Select Area window is tiny and not resizable, making it hardly usable.

I tried to resize the window using KWin window rules to no avail.

**Steps to reproduce**

1. Open Kooha
2. Select "Capture a Selection of Screen"
3. Click "Record"

**Expected behavior**

The window is of reasonable size as in https://github.com//SeaDve/Kooha/issues/52#issuecomment-1260339700

**Relevant logs, screenshots, screencasts, etc.**

![image](https://github.com/SeaDve/Kooha/assets/44045911/94837ccf-1eeb-41a2-b624-b8da598b7855)

**Comment by kidonng** [comment]
The culprit seems to be 12fde0009ec1ac11e4df140019c1a35066321447, as things look OK on 2.2.3, where "scale_factor" is 0.4, though still a little small for me.

Nonetheless, it would be better if the window is resizable.

**Comment by SeaDve** [comment]
> The culprit seems to be https://github.com/SeaDve/Kooha/commit/12fde0009ec1ac11e4df140019c1a35066321447, as things look OK on 2.2.3, where "scale_factor" is 0.4, though still a little small for me.

Thanks for looking at it! Do you have fractional scale enabled?

> Nonetheless, it would be better if the window is resizable.

I would prefer that too indeed

**Comment by kidonng** [comment]
> Thanks for looking at it! Do you have fractional scale enabled?

Yes, I have enabled 150% scale via system settings.

**Comment by NotSqrt** [comment]
And it might be helpful to have the option to "remember the previously selected zone" !

**Comment by SeaDve** [comment]
Fixed via https://github.com/SeaDve/Kooha/discussions/263

**Comment by SeaDve** [comment]
> And it might be helpful to have the option to "remember the previously selected zone" !

This is now implemented :D
