### ISSUE TITLE
Failed to start recording

### ISSUE THREAD

**Issue by randunel** [SeaDve/Kooha#262]
**Affected version**

2.2.4

**Bug summary**

Does not record

**Steps to reproduce**

1. open kooha
2. click Record

**Expected behavior**

Starts recording

**Relevant logs, screenshots, screencasts, etc.**

Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Interaction was ended in some other way with response Variant { ptr: 0x56529537d780, type: VariantTy { inner: "a{sv}" }, value: "@a{sv} {}" }

I followed the debugging guide linked and my system starts being different at

```
< "/proc/$(pidof xdg-desktop-portal)/environ" tr '\0' '\n' | grep '^XDG_CURRENT_DESKTOP='
XDG_CURRENT_DESKTOP=Regolith:GNOME-Flashback:GNOME
```

I'm using the `picom` compositor.

**Comment by SeaDve** [comment]
Thanks for the bug issue. This particular issue has already been reported in https://github.com/SeaDve/Kooha/issues/202, so this report is being marked as a duplicate.
