### ISSUE TITLE
Gnome Circle

### ISSUE THREAD

**Issue by mvsrgc** [SeaDve/Kooha#268]
Hi, the last [request](https://github.com/SeaDve/Kooha/issues/22) to try to get this app on Gnome Circle was in 2021.
Would it be possible to try again now that it's 2024? :)

**Comment by SeaDve** [comment]
Kooha actually once became a Circle app, but I decided to get it removed: https://gitlab.gnome.org/Teams/Circle/-/issues/174

**Comment by mvsrgc** [comment]
Fair enough :)
