### ISSUE TITLE
Let the user know where to find the recording

### ISSUE THREAD

**Issue by Vinnl** [SeaDve/Kooha#28]
After I press "Stop" during recording, the interface just goes back to the initial state and I have no idea whether the recording succeeded. A notification saying it finished successfully and ideally also with a link to view the recording or the location it has been stored at would be very useful.

(I'm on Ubuntu 20.04 if this is actually supposed to be shown.)

**Comment by SeaDve** [comment]
I had been considering this feature, but I'm worried on showing the notification too frequently, that it became annoying.

By default, it saves the recording on Videos folder similar to how GNOME Screenshot save in Pictures folder.

**Comment by diegogangl** [comment]
A button in the main menu could help, something like "Show last recording".

**Comment by fastrizwaan** [comment]
Yes, a menu entry or a button with "Show the Files" (ark)  or "Show Recordings" or "Open Videos Folder" will do the job.
![Screenshot from 2021-03-23 12-44-01](https://user-images.githubusercontent.com/1161682/112107894-8cb68980-8bd5-11eb-88f8-2b406985d79b.png)

**Comment by SeaDve** [comment]
Already pushed this on master, will come on 1.0.6

**Comment by SeaDve** [comment]
Since this is already implemented, gonna close this.
