### ISSUE TITLE
Recording stopwatch's seconds counter increments more than once per second

### ISSUE THREAD

**Issue by nekohayo** [SeaDve/Kooha#280]
**Affected version**

git `main`, and the stable version too, IIRC.

**Bug summary**

The seconds counter refreshes at a seemingly variable rate. See video below.

**Steps to reproduce**

In my case, it happens simply by recording a portion of the screen with microphone active. I haven't tried other combinations.

This may or may not be influenced by system load or idleness, such as whether or not you move the mouse cursor, I am not sure.

Tested on the Wayland version of GNOME 45.3 on Fedora 39.

**Relevant logs, screenshots, screencasts, etc.**

[Kooha stopwatch seconds wonkiness.webm](https://github.com/SeaDve/Kooha/assets/479401/8e1f17ac-6902-4929-a7f2-8712923eec42)

**Comment by SeaDve** [comment]
We could provide our own timer, like pre-2.0 versions, it would increment more consistently, but it wouldn't be as accurate.

**Comment by nekohayo** [comment]
Oh yes indeed, it seems the issue does not happen with the MP4 encoder.

By the way, it might also be worth being more specific in the UI about which video codecs are used (H.264 vs VP8 vs VP9 vs AV1…) with some sort of indication of which one(s) tend to give the best performance vs compatibility etc.? Because container formats like MP4, WebM and Matroska are not really that useful to make a decision...

**Comment by SeaDve** [comment]
Thanks for the confirmation.

> By the way, it might also be worth being more specific in the UI about which video codecs are used (H.264 vs VP8 vs VP9 vs AV1…) with some sort of indication of which one(s) tend to give the best performance vs compatibility etc.? Because container formats like MP4, WebM and Matroska are not really that useful to make a decision...

Feel free to open another issue about that one. I would close this as non-actionable/won't fix.
