### ISSUE TITLE
"There's no way that AdwDialog Preferences widget is going to fit inside me! 😳" 

### ISSUE THREAD

**Issue by nekohayo** [SeaDve/Kooha#281]
**Affected version**

git `main` built with GNOME Builder, running on Wayland GNOME 45.3 on Fedora 39.

**Bug summary**

It seems you are using AdwDialog since d24b528dde. However, unless you have plans to Enlarge Your MainWindow™, I don't think AdwDialog is meant to be compatible with its tiny non-resizeable size:

[Kooha libadwaita preferences dialog trolling.webm](https://github.com/SeaDve/Kooha/assets/479401/dc94d4e2-ffc2-4ec1-a4cb-599ab81ca1c8)

**Comment by SeaDve** [comment]
Previous versions of the libadwaita don't support unresizable windows, later versions should fallback to a full-blown window. Try updating your GNOME Sdk

**Comment by SeaDve** [comment]
On the other hand, there is a development branch to redesign the app's main interface: https://github.com/SeaDve/Kooha/discussions/263

**Comment by SeaDve** [comment]
Hi, I think this can be closed?
