### ISSUE TITLE
Support for pipewire VideoTransform information

### ISSUE THREAD

**Issue by IlyaMZP** [SeaDve/Kooha#284]
**Feature summary**
I use xdg-desktop-portal-wlr on sway and currently if I record my flipped monitor with Kooha, the video is flipped too. This is expected, as the portal implementation doesn't transform its buffers. But it would be great if Kooha could receive the VideoTransform meta information from pipewire and apply videoflip filter to it.

**How would you like it to work**

AFAIK Kooha uses pipewiresrc from gstreamer, which sends an event with an `image-orientation` tag. It should be possible to use `videoflip` element and change its `method` property (or maybe save rotation in video metadata) if we receive the image orientation event. But I'm not sure how it would affect other elements in the pipeline.

**Relevant links, screenshots, screencasts, etc.**

This feature has been added to OBS: https://github.com/obsproject/obs-studio/pull/7762
This feature request is related to #250 
An example python script that listens for the event: https://gist.github.com/IlyaMZP/fe75ca1df4cbe058fbcff489c8514e4c

**Comment by SeaDve** [comment]
Thanks for reporting! I'll check about it.

**Comment by SeaDve** [comment]
I'm not sure if this should be implemented upstream on `pipewiresrc`, but we'll see.

**Comment by IlyaMZP** [comment]
> I'm not sure if this should be implemented upstream on `pipewiresrc`, but we'll see.

It is implemented, here is the relevant code in pipewiresrc: https://github.com/PipeWire/pipewire/blob/f2f60ee0ec77cb119dbf6503fcba2d3ebb961532/src/gst/gstpipewiresrc.c#L615C7-L615C25

**Comment by SeaDve** [comment]
I see, thanks. Kooha's side, it is.

**Comment by SeaDve** [comment]
Hi, I have pushed a fix in the main branch. If you have the time, please test it. Thanksss!

**Comment by IlyaMZP** [comment]
> Hi, I have pushed a fix in the main branch. If you have the time, please test it. Thanksss!

Awesome, it works! Didn't know videoflip could process video orientation automatically, that's nice to know. Thanks!

**Comment by SeaDve** [comment]
Thanks for confirming!
