### ISSUE TITLE
Kooha records corrupted / empty video I can't send to any platform.

### ISSUE THREAD

**Issue by Suero152** [SeaDve/Kooha#288]
**Affected version**

- io.github.seadve.Kooha 2.2.4
- Flatpak: false
- Experimental: false

- Language: en_US, en, C

- Distribution: Manjaro Linux
- Desktop Session: plasmawayland
- Display Server: wayland

- GTK 4.12.5
- Libadwaita 1.4.4
- GStreamer 1.22.10
- Pipewire 1.0.3

**Bug summary**

Kooha records corrupted video I can't send to Discord, Whatsapp, Github, Streamable, Imgur, Google Drive and probably I can't send to any platform.

I can reproduce the video inside a video player tho, but every time I try to upload, platforms say it is empty.

**Steps to reproduce**

1. Record a video with Wayland, MP4 and 60 fps.
2. Try to upload to Discord or Whatsapp

**Expected behavior**

I expected to the upload to be successful.

**Relevant logs, screenshots, screencasts, etc.**

![Screenshot_20240311_224333](https://github.com/SeaDve/Kooha/assets/62967229/3b7dd7e2-d4b7-48af-86e5-06f0617260a3)

![Screenshot_20240311_224322](https://github.com/SeaDve/Kooha/assets/62967229/8170ca72-e304-4ad0-ad6d-46ce59251369)

![Screenshot_20240311_224316](https://github.com/SeaDve/Kooha/assets/62967229/af5ad182-5e99-45ca-b520-7f31dd62db04)

![Screenshot_20240311_224425](https://github.com/SeaDve/Kooha/assets/62967229/a74a71c9-b57b-4447-8351-0f8b2cb0dfdd)

**Comment by SeaDve** [comment]
Can you reproduce it on Flatpak?

**Comment by Suero152** [comment]
> Can you reproduce it on Flatpak?

Yeah, the video I record it's also corrupt. ( Also the UI is very weird in Flatpak version XD )

- io.github.seadve.Kooha 2.2.4
- Flatpak: true
- Experimental: false

- Language: en_US, en, C

- Distribution: GNOME 45 (Flatpak runtime)
- Desktop Session: plasmawayland
- Display Server: wayland

- GTK 4.12.5
- Libadwaita 1.4.3
- GStreamer 1.22.10
- Pipewire 0.3.83


![Screenshot_20240311_230120](https://github.com/SeaDve/Kooha/assets/62967229/5b7fe293-e3ec-41aa-b1c8-047d46ea7b0c)
![Screenshot_20240311_230102](https://github.com/SeaDve/Kooha/assets/62967229/d5e6d16e-ac3e-4aa9-9cd7-d88565c5160a)

**Comment by SeaDve** [comment]
If you may, you can also test the version in the main branch. A lot of stability fixes has been done, and it might have been fixed.

**Comment by Suero152** [comment]
I discovered it was an issue with Brave itself ( happening in Discord too since they are both chromium ) this is very odd, switching broswers worked.

**Comment by SeaDve** [comment]
That's weird indeed 🤔. What browser worked?

**Comment by Suero152** [comment]
> That's weird indeed 🤔. What browser worked?

Switching to Firefox solved it. Probably not Brave's fault but chromium's.

https://community.brave.com/t/brave-doesnt-recognize-upload-files/442358
https://community.brave.com/t/impossible-to-upload-file-with-brave/467307
https://community.brave.com/t/unable-to-upload-anything/41484
