### ISSUE TITLE
No feedback when recording audio failed

### ISSUE THREAD

**Issue by Vinnl** [SeaDve/Kooha#29]
With either the microphone or speaker button toggled on, when I record my screen I get a recording file just fine, but there's no audio. I'm not familiar enough with the stack to know why (something about me being on Ubuntu 20.04 without Pipewire? :shrug: ), but if there's a straightforward reason, it'd be great to get some feedback on that it won't work, and ideally (if possible) with some guidance on how to resolve it.

**Comment by SeaDve** [comment]
version?

**Comment by SeaDve** [comment]
With the feedback, if it is recording audio, It could show a visualizer. Although with this fix, it will require a redesign. Alternatively, you can check on gnome-settings's audio visualizer.

**Comment by SeaDve** [comment]
I started working on fixing this issue, I'll send you some screenshots on how it will look like. Would love to hear your opinion.

**Comment by SeaDve** [comment]
![image](https://user-images.githubusercontent.com/64297935/111769821-9d6cb400-88e4-11eb-865a-5a1525b1384e.png)

**Comment by SeaDve** [comment]
I did a couple of changes with v1.0.4 wherein it will get the default selected device based on the GNOME settings. Tip: you can select the device there and even test if it is working, and it should mirror with Kooha.

**Comment by rugk** [comment]
In addition to that, IMHO, it should display an error ui.
Also in my case it is the internal audio it should record, which it does not.

**Comment by SeaDve** [comment]
> In addition to that, IMHO, it should display an error UI.

With this, it would be possible but unreliable

> Also in my case it is the internal audio it should record, which it does not.

Could you provide more information about this

**Comment by rugk** [comment]
I wrote it in a new issue and investigated it in more detail by doing so: https://github.com/SeaDve/Kooha/issues/49 (TL;DR: it does not affect all sounds)

**Comment by Vinnl** [comment]
Sorry about the radio silence - something went wrong with my email notifications so I'm just seeing this now.

Trying it out now, it appears that Kooha can record audio just fine, which is great, but also unfortunately means that I can no longer reproduce the error to test out the error feedback :) The visualisation looks great though!

**Comment by SeaDve** [comment]
I think it is pretty much impossible/workaroundy to determine if it actually recorded the audio. Since the audio problem is fixed, and you can determine if the mic/audio works with system settings. I think it is safe to say that I can close the issue.
