### ISSUE TITLE
No icon and name in gnome-software

### ISSUE THREAD

**Issue by Vinnl** [SeaDve/Kooha#30]
This is the listing of Kooha on Ubuntu 20.04:

![image](https://user-images.githubusercontent.com/4251/111640194-4095ce80-87fc-11eb-9e81-1bf4e86bcdc7.png)

**Comment by SeaDve** [comment]
Hmm, it looks good on Fedora, maybe Ubuntu issue, or maybe check for updates. I'll investigate on this one.

**Comment by SeaDve** [comment]
![Screenshot from 2021-03-19 09-55-17](https://user-images.githubusercontent.com/64297935/111720621-3c6bbe80-8899-11eb-816d-26ce3a679e38.png)
Here is Fedora's.

**Comment by SeaDve** [comment]
Since this is not an issue on app itself, gonna close this
