### ISSUE TITLE
Add an option to be able to stretch the window (Remove Max-Width)

### ISSUE THREAD

**Issue by RyanOrigens** [SeaDve/Kooha#300]
The application works well on GNOME/KDE and other desktop environments. However, in a tiling window manager, it lacks the option for Alt+Tab functionality. Consequently, the window itself would need to be moved to another workspace, resulting in a very small window within the entire workspace.

Feature Request: Implement a toggleable option to remove the maximum width constraint.

**Comment by RyanOrigens** [comment]
Update:

I've seen the redesign update, and it would fix my issue, so I'm going to be closing this issue.

https://github.com/SeaDve/Kooha/discussions/263

**Comment by coffebar** [comment]
I would like kooha can be tiled on tiling window managers.
