### ISSUE TITLE
Pop up child windows open tiled instead of float

### ISSUE THREAD

**Issue by mooncoffee1** [SeaDve/Kooha#304]
**Affected version**

idk the newest niri packge from arch linux

**Steps to reproduce**

1. Open thunar for example
2. Click on a file and press F2 to rename it, or just rename option 
3. The rename pop up will open as new window, instead of small floating pop up

**Expected behavior**

That niri to understand these child windows of the app, and make that floating with the correct width and height not tilling them as windows

**Relevant logs, screenshots, screencasts, etc.**

**Comment by YaLTeR** [comment]
You sure you opened this issue on the right repo? Anyhow, this issue is already tracked, https://github.com/YaLTeR/niri/issues/122

**Comment by SeaDve** [comment]
Gotta close this since it seems to be not relevant to Kooha, thanks!
