### ISSUE TITLE
Recording outputs 0kb file, no errors reported via UI

### ISSUE THREAD

**Issue by vitriol** [SeaDve/Kooha#33]
Hi, running on arch + wayland, latest packages. There are no errors reported, it seems to run fine, but when I hit stop and go check the destination directory there is a file called 'Kooha-2021-03-21-22:34:26.webm' with size 0. 
running from the command line I get the following error:

```
Error: gst-resource-error-quark: Resource not found. (3) ../gstreamer/plugins/elements/gstfilesrc.c(536): gst_file_src_start (): /GstPipeline:pipeline1/GstFileSrc:filesrc0:
No such file "/tmp/tmpvideo.mkv"
```

Doesn't matter if I select mkv or webm, result is the same. Installed from AUR

**Comment by SeaDve** [comment]
I haven't done a lot on testing in AUR,  since, I do not have arch installed, I do recommend on using flatpak package. Although I'll investigate

**Comment by vitriol** [comment]
Just installed flatpak version, but same issue. What's interesting is that if I don't check the mic or the audio options, I don't even get a file created at all. If I check either, a 0bytes file is created in expected destination. No other output.
No idea what this means, it should work with flatpak, regardless of my other system settings, right? Would love to be able to screencast with audio

**Comment by SeaDve** [comment]
Hm, that's weird. Are you on Gnome?

**Comment by vitriol** [comment]
Gnome. Normally I would dismiss the aur one since god knows what custom packages I've installed, but the flatpak one is making think there's more to this. Any extra verbosity options I can turn on to find more clues?

**Comment by SeaDve** [comment]
Unfortunately, I haven't put debugging features. Does `ctrl+alt+shift+r` works?

**Comment by vitriol** [comment]
ctrl+alt+shift+r worked just fine last time I used it few weeks back, and now strangely it doesn't. Wonder how I can debug that one
Ok, I guess I should close this, since it's not related to your app?
Thanks though

**Comment by SeaDve** [comment]
It is related, but not Kooha, more like an upstream issue. Maybe a gnome shell update broke it? Also, thanks also for participating!

**Comment by vitriol** [comment]
Upstream gnome-shell bug actually, should be closed with the next update in the repos. 

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3810

**Comment by uninhm** [comment]
I have exactly the same issue here

**Comment by SeaDve** [comment]
feel free to open another issue

**Comment by SeaDve** [comment]
anyway, the backend is rewritten entirely, and it may not exist on main branch

**Comment by uninhm** [comment]
> feel free to open another issue

It's better to reopen this one, it doesn't make sense to copy exactly the same description and open a new one.

**Comment by SeaDve** [comment]
im thinking that it may disturb the last one who open this issue, spam mail stuffs, since i might ask some question to troubleshoot the problems

**Comment by SeaDve** [comment]
does ctrl+alt+shift+r works?
what distro?
how did you installed it? (i.e. flatpak, aur)

do you mind building the latest git version from source, if the issue still exist?

**Comment by uninhm** [comment]
What should Ctrl + Alt + r do?
Distro: Void Linux
I built the latest release

**Comment by SeaDve** [comment]
Somehow, github doesn't notify me on your reply, sorry

The `ctrl+alt+shift+r` is suppose to trigger gnome-shell's built in screen recorder, which is what version 1.2.1 and below use.

**Comment by uninhm** [comment]
Solved!! The issue was that `pipewire` has to be run manually.

**Comment by SeaDve** [comment]
i think we can close this now
