### ISSUE TITLE
Width is not divisible by 2

### ISSUE THREAD

**Issue by skerit** [SeaDve/Kooha#34]
I've had some problems with recorded videos not working on certain sites. Getting weird errors and such.
So I thought I'd convert from webm to mp4, and then I got this error in ffmpeg:

```
[libx264 @ 0x555da2f84840] width not divisible by 2 (2627x1628)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```

Maybe this is why I got some errors on those sites?

Would it be possible to make the videos width & height always divisible by 2?
Either by always forcing the selection dimensions to be divisible by 2, or by post-processing the video somehow?

Right now I cleared it up with this ffmpeg command:

     ffmpeg -i input.webm -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" output-pad.webm

(I first tried to convert it to an mp4, but that took forever and somehow caused the framerate to drop)

**Comment by SeaDve** [comment]
Did you record with Selection mode? What is your display resolution?

**Comment by SeaDve** [comment]
Eitherway, I have a fix for this. Although, it might not arrive sooner in flatpak.

**Comment by SeaDve** [comment]
In other side, this is more like FFmpeg's fault, you can use gstreamer to convert mkv to mp4 without these issues. Pipeline would be something like `filesrc ! matroskademux ! vp8dec ! x264enc ! filesink`. You won't need to do this in the future.

**Comment by skerit** [comment]
Everything is OK when recording fullscreen, it's all divisible by 2 :) (Although I won't really ever use that feature, because I have three 4K monitors, and I hardly ever need to capture all three screens at once)

**Comment by SeaDve** [comment]
I'll push the fix in v1.1.0 together with mp4 : D

**Comment by SeaDve** [comment]
https://github.com/SeaDve/Kooha/tree/evenarea Have pushed the fixed in this branch. If you wanna test it, you can build from source.

**Comment by SeaDve** [comment]
Feel free to close this when fixed, thanks!
