### ISSUE TITLE
60 fps - for game recording

### ISSUE THREAD

**Issue by fastrizwaan** [SeaDve/Kooha#35]
Can we have 60 fps too, for game recording?

This one is less than 30 as mpv says in info
https://user-images.githubusercontent.com/1161682/111961544-32ef8a00-8b17-11eb-9406-0260cfb59325.mp4

![fps](https://user-images.githubusercontent.com/1161682/111961629-4a2e7780-8b17-11eb-8d05-9312f000d206.png)

**Comment by SeaDve** [comment]
Yes, by making it as the default soon, although as an option it might not happen due to design issues (Should consider a new design).

**Comment by SeaDve** [comment]
I have added an fps option that could be changed through settings

**Comment by SeaDve** [comment]
https://github.com/SeaDve/Kooha#hidden-configuration-options
Here is the instruction btw.

**Comment by fastrizwaan** [comment]
with simplescreenrecorder 60 fps it records smoothly https://youtu.be/ynD30w_U1T8

![Screenshot from 2021-03-29 13-47-18](https://user-images.githubusercontent.com/1161682/112807269-52e1f900-9095-11eb-86f7-c0e61d03ec71.png)

**Comment by SeaDve** [comment]
Oh no

**Comment by fastrizwaan** [comment]
> Oh no, I was using the mobile github app, and I didn't realized I edited your comment, instead of creating a reply.

No problem. https://github.com/SeaDve/Kooha#hidden-configuration-options flikering is happeing with kooha on intel gpu. I'll check with nvidia soon.

**Comment by SeaDve** [comment]
I also use intel gpu, HD 630 to be exact.

**Comment by SeaDve** [comment]
Since this is already implemented, gonna close this, but feel free to reopen
