### ISSUE TITLE
Always on Top for selection recording 

### ISSUE THREAD

**Issue by arpu** [SeaDve/Kooha#36]
Hey,

would be nice to have a option for always onTop if i use selection Recording

**Comment by SeaDve** [comment]
The Kooha window, or the window being recorded?

**Comment by arpu** [comment]
The Kooha Window, because if i want stop the recording i always get the Activity Window at the end of the Video

**Comment by arpu** [comment]
not sure this is still needed, because if i use the keyboard shortcuts all works fine for me

**Comment by hedwiggggg** [comment]
Seems to be still needed, because the keyboard shortcuts are only working for me, if the recorder window is the active window.
