### ISSUE TITLE
Add support for Endless Shell

### ISSUE THREAD

**Issue by LeandroStanger** [SeaDve/Kooha#4]
![Captura de tela de 2021-03-13 21-17-45](https://user-images.githubusercontent.com/26097419/111053313-973c8a80-8441-11eb-9c0c-a163379e9496.png)

**Comment by SeaDve** [comment]
Now fixed in master. I will push it on Flathub.
Let me know if it got fixed, thanks!

**Comment by SeaDve** [comment]
The patches are now released in flathub.

**Comment by LeandroStanger** [comment]
![Captura de tela de 2021-03-14 08-52-09](https://user-images.githubusercontent.com/26097419/111067417-e666d780-84a2-11eb-860e-27b2f342d32f.png)
