### ISSUE TITLE
Send notification when the video file is completed.

### ISSUE THREAD

**Issue by janoxakes** [SeaDve/Kooha#40]
Once the recording is over, the final output video file starts being populated. Depending on multiple factors, this can take some time and the only way to ensure that the process is over is to refresh the file browser until modification time stops increasing.

A notification letting the user know that the process is happening and another informing the process is over would be very useful, specially when the intention is to shut down after a recording.

In any case, amazing software. Many thanks!

**Comment by SeaDve** [comment]
Glad to say that, this feature has recently been pushed to flathub, real quick!

**Comment by janoxakes** [comment]
You should be proud! 
As you said, the update was there waiting to be pulled. Thanks :)
