### ISSUE TITLE
Suggestion: Pause Recording

### ISSUE THREAD

**Issue by liimee** [SeaDve/Kooha#41]
would be cool if we could pause recording and continue it later :D

**Comment by SeaDve** [comment]
In the present recording back-end, it is almost impossible without ugly workarounds, although when Kooha moves to freedesktop portal ScreenCast, it will be easier.

**Comment by SeaDve** [comment]
#65 pause feature on prorgress :D

**Comment by SeaDve** [comment]
I'll close this in favor of #112, thanks!
