### ISSUE TITLE
Support for Window Managers

### ISSUE THREAD

**Issue by im-n1** [SeaDve/Kooha#43]
I'm getting this error when I run the program.

```
Traceback (most recent call last):
  File "/app/share/kooha/kooha/main.py", line 63, in do_activate
    self.window = KoohaWindow(application=self)
  File "/app/share/kooha/kooha/window.py", line 58, in __init__
    desktop_environment = os.environ['XDG_CURRENT_DESKTOP']
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_CURRENT_DESKTOP'
```

**Comment by SeaDve** [comment]
what are your system informations? distro etc.

**Comment by im-n1** [comment]
- debian testing
- bspwm
- python 3.9.2

**Comment by SeaDve** [comment]
Ahh, the error is coming from the desktop environment check wherein it tests if you are using gnome, but since you are not using a DE it might not work. I do recommend RecApp.

**Comment by im-n1** [comment]
So this app is Gnome-only?

**Comment by SeaDve** [comment]
Yes, as off now. Although, I'm working on support for other in v2.0

**Comment by SeaDve** [comment]
#65 If your window manager support org.freedesktop.portal.Screencast, it should also work there

**Comment by SeaDve** [comment]
Hi, would like to confirm if kooha now works on certain window managers. it would be great to build main branch or this already built package https://github.com/SeaDve/Kooha/suites/3015646991/artifacts/68284776

**Comment by SeaDve** [comment]
Closing this as completed.
