### ISSUE TITLE
Record button and primary menu link is odd

### ISSUE THREAD

**Issue by bertob** [SeaDve/Kooha#46]
When two buttons are linked it implies some kind of semantic grouping, so it doesn't make sense to do it between record button and primary menu. I'd either just unlink them, or maybe move the primary menu to the top left and style it like the close button, like e.g. [Typography](https://flathub.org/apps/details/org.gnome.design.Typography) does.

![image](https://user-images.githubusercontent.com/1908896/113773032-bfa86380-9725-11eb-972f-154459994e96.png)

**Comment by SeaDve** [comment]
Thanks! Here is how it looks like.
![image](https://user-images.githubusercontent.com/64297935/113947149-90384a80-983c-11eb-9fac-fd95a4b2ecf1.png)

Although, I linked them together since the settings that the menu would contain is highly related to recording.

**Comment by bertob** [comment]
Given the simplicity of the UI and basically everything being an option related to the recording I don't think it's necessary to link the options to the record button, your last screenshot looks great to me :+1:

**Comment by SeaDve** [comment]
Already merged to master, gonna close this thankss
