### ISSUE TITLE
Multi-monitor support (record a specific screen)

### ISSUE THREAD

**Issue by garrett** [SeaDve/Kooha#48]
Firstly: Thanks for Kooha! It's a great app.

I have multiple monitors... usually 3 to be precise. When using Kooha, it records all three, with a gap where the resolutions do not match.

What I'd like is for Kooha to record a specific monitor. 

Some ideas:

- A "simple" solution might be to let Kooha record only the screen it is currently on.

- A more elaborate solution could be to have a picker to choose the screen to record. 
  - It could either remember the last used, or if one has not been used yet, default to the current screen.
  - This would allow someone to record a screen without having the Kooha UI in the video recording... if they have more than one monitor, of course.

**Comment by SeaDve** [comment]
This would be possible when I replace the backend with freedesktop Screencast :D . For now, you can work around with the selection mode

**Comment by Turbine1991** [comment]
> This would be possible when I replace the backend with freedesktop Screencast :D . For now, you can work around with the selection mode

Is this transition in the near-term pipeline? Wonderful app by the way.

**Comment by SeaDve** [comment]
#65 Work on progress

**Comment by SeaDve** [comment]
merged to main
