### ISSUE TITLE
GNOME volume change sounds of top bar are not recorded

### ISSUE THREAD

**Issue by rugk** [SeaDve/Kooha#49]
Use Kooha like this:

![grafik](https://user-images.githubusercontent.com/11966684/113995833-e4e8bf00-9856-11eb-992a-ad257591d4d8.png)

video:
[Kooha-2021-04-08-10:41:07.zip](https://github.com/SeaDve/Kooha/files/6277315/Kooha-2021-04-08-10.41.07.zip)

The sounds of the GNOME volume change of the top bar are not recorded.
I just noticed by using the "test" in the GNOME audio _settings_ that other sounds are apparently recorded properly.

```
$ flatpak run io.github.seadve.Kooha                  
Default sink: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor 
Default source: None
```

**Comment by SeaDve** [comment]
Hmm, so it might be more of an upstream gstreamer issue

**Comment by rugk** [comment]
Dunno, tell me what I should report where and I'll do it… (or do it by yourself, if you need some further verification)

**Comment by SeaDve** [comment]
I might need a couple of information 
* Are you on wayland?
* Is it also reproducible with other recorder such as GNOME Sound Recorder?
* What are the sounds that aren't recorder? For example browser, games, or music player? or just system sounds?

**Comment by rugk** [comment]
> Are you on wayland?

Yes.
Fedora 33
GNOME 3.38.5

> Is it also reproducible with other recorder such as GNOME Sound Recorder?

That does only record the microphone, does not it?

> What are the sounds that aren't recording? For example browser, games, or music player? or just system sounds?

Only discovered this one, so far. Just tried a YouTube video. It works.
GNOME Music works.
0 A.D. works, too.

**Comment by SeaDve** [comment]
> That does only record the microphone, does not it?

Yes,  GNOME sound recorder uses the same backend has Kooha

Although, it seems that this doesn't affect critical applications and works, I will not mark this as a priority.

**Comment by rugk** [comment]
> p.s. I just watched the file from the zip file, everything seems to be fine including system audio.

Wtf, am I stupid? I just watched it again and you're right…
I could swear I did not hear anything.
Maybe… I did not… … unmute my speaker? :see_no_evil: 

Oh I'm so sorry, what a waste of time.
Just good I did attach the original video #alwaysGoodBugReporting.

So… closing I guess.
