### ISSUE TITLE
TypeError: init() missing 1 required positional argument: 'argv'

### ISSUE THREAD

**Issue by yochananmarqos** [SeaDve/Kooha#5]
I just built 1.0.0 and tried from the latest [commit](9ccc8a3daf79163503ea536bfd3331f1b8a3b74e):

```
Traceback (most recent call last):
  File "/usr/bin/kooha", line 40, in <module>
    from kooha import main
  File "/usr/share/kooha/kooha/main.py", line 28, in <module>
    Gst.init()
TypeError: init() missing 1 required positional argument: 'argv'
```

Meson 0.57.1
Python 3.9.2
Manjaro GNOME

**Comment by SeaDve** [comment]
https://github.com/SeaDve/Kooha/commit/57d7bb3889e8e4b43ef023fd42617f885c6e402f
Try the latest commit, thanks!

**Comment by yochananmarqos** [comment]
That fixed it and the program seems to work fine. Thanks!
