### ISSUE TITLE
draw selected region on screen

### ISSUE THREAD

**Issue by tronta** [SeaDve/Kooha#50]
if a region has been selected, it would be great if it could be drawn on the screen, so in case one is moving windows around, it is easy to see what is being recorded.

**Comment by SeaDve** [comment]
This would be possible to implement now, since kooha now handles area selection

**Comment by SeaDve** [comment]
This is unfortunately not practically possible with current desktop APIs. Closing this for now since it is not realistically attainable any time soon.
