### ISSUE TITLE
No quality slider

### ISSUE THREAD

**Issue by enthdegree** [SeaDve/Kooha#51]
Doesn't have a video quality slider. 

Adding this feature amounts to exposing to the user some of the hardcoded constants in the 1 or 2 lines in _recorders.py_ that handle the program's real work. 

Unfortunately the way it is written this would require propagating this new free parameter through so many layers of schemas I don't have time to do it myself.

**Comment by SeaDve** [comment]
I have rewritten it on the mp4 branch to make it less hardcoded. Eitherway, I don't plan on adding quality slider.

**Comment by enthdegree** [comment]
Just curious, is there some advantage vp8enc offers vs others?

**Comment by SeaDve** [comment]
Had tried vp9enc but it is very stuttery. X264enc would also be great but it has some packaging issue especially on fedora.

In the future when I migrate the backend to become independent of gnome-shell's dbus interface. It would be easier to modify the encoders, quality etc.

**Comment by enthdegree** [comment]
Excellent, thanks for the information.

**Comment by SeaDve** [comment]
duplicate of #31
