### ISSUE TITLE
selection size

### ISSUE THREAD

**Issue by Framelony** [SeaDve/Kooha#52]
i like this app, simple and functional. if i can suggest a new features when i use resize window to capture i need the size of the selection to be sure to make a 1920X1080 windows and put the app i need to recorder inside. and a border of the selecion i am using. 
thanks

**Comment by SeaDve** [comment]
I think this will need upscaling the footage.

**Comment by SeaDve** [comment]
Fixed through https://github.com/SeaDve/Kooha/commit/dd806ad82b3cbb867f7550793576428edfe95dba.

Kooha now as a proper area selector tool.

![image](https://user-images.githubusercontent.com/64297935/192681050-31e21490-35c9-4fb9-b570-eea8340b5204.png)
