### ISSUE TITLE
Kooha crashes on Gnome 40

### ISSUE THREAD

**Issue by molitona** [SeaDve/Kooha#54]
I've tested Kooha on Gnome 40 and when I click record button it crashes and says "Kooha is not responding", any solution ?

**Comment by SeaDve** [comment]
Hi, could you describe it a little more. Like how to replicate it, and your system informations.

**Comment by molitona** [comment]
I'm using Arch.
Open the app from GUI/Terminal, then click Record button --> It crashes with the above message.
Here what Terminal shows

(io.github.seadve.Kooha:78774): Gtk-WARNING **: 08:14:50.791: Theme directory 32/apps of theme Fantasy-blue-dark has no size field

Default sink: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor 
Default source: alsa_input.pci-0000_00_1b.0.analog-stereo
Traceback (most recent call last):
  File "/usr/share/kooha/kooha/window.py", line 72, in on_start_record_button_clicked
    self.delay_timer.start(delay)
  File "/usr/share/kooha/kooha/timers.py", line 63, in start
    self.function()
  File "/usr/share/kooha/kooha/window.py", line 98, in start_recording
    self.video_recorder.start(directory, framerate, show_pointer)
  File "/usr/share/kooha/kooha/recorders.py", line 143, in start
    self.gnome_screencast.call_sync(
gi.repository.GLib.Error: g-io-error-quark: Timeout was reached (24)

**Comment by SeaDve** [comment]
Have you tried using `ctrl+shift+alt+R`. It might be an upstream issue with the gnome shell.

**Comment by molitona** [comment]
This shortcut doesn't do anythink in Gnome 40.

-------- Original Message --------

**Comment by SeaDve** [comment]
Hm, I think this might be it.
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3810

Also, the same issue that was submitted here
https://github.com/SeaDve/Kooha/issues/33

**Comment by molitona** [comment]
ah, then it's gnome-shell bug ?

-------- Original Message --------

**Comment by SeaDve** [comment]
Kind of, but more like pipewire

**Comment by molitona** [comment]
What do you mean by pipewire ?

-------- Original Message --------

**Comment by SeaDve** [comment]
I think it is similar to something like pulseaudio but pipewire can handle both audio and video

**Comment by molitona** [comment]
And, what's the solution then ?

-------- Original Message --------

**Comment by SeaDve** [comment]
It seems to already fixed, and should come soon

**Comment by molitona** [comment]
Ok, thanks!

-------- Original Message --------

**Comment by Leleat** [comment]
Kooha also crashes for me on GNOME 40. GNOME's built-in screen recorder (`Ctrl` + `Shift` + `Alt` + `R`) works, so maybe it's a different issue than OP's?

If I press the 'Record' button, the orange dot appears in the status area nothing else happens anymore. After that Kooha doesn't respond anymore (i. e. I don't get the `Recording` screen) and if I try to click anything, I get GNOME's `Force quit/Wait` message and the orange dot doesn't dissapear from the status area...

Anything I can do to help debug this? I am on Fedora 34 with Kooha from Flathub.

**Comment by SeaDve** [comment]
What version are you on?

**Comment by Leleat** [comment]
> What version are you on?

The current one from flathub (1.1.3 according to the about page)

**Comment by SeaDve** [comment]
I think it might be the new pipeline, if it is okay to you, you can try reproducing the error with this version https://github.com/SeaDve/Kooha/suites/2648636877/artifacts/58200788

**Comment by SeaDve** [comment]
Other than that, reproducing the issue then running `journalctl | grep org.gnome.Shell.Screencast` and pasting the output here would also be great.

**Comment by Leleat** [comment]
excact Steps I did:

1. Download artifact
2. install with `flatpak install PATH_TO_FILE`

Same problem happens. Kooha doesn't react anymore after pressing the `Record` button. 

- `journalctl | grep "JS ERROR"` didn't give _anything_ after reproducing the error. I started Kooha at 14:24 but the last entry is from 14:20.

- I also followed the journal with `journalctl -f` while reproducing the error and there is some pipewire stuff. Don't know, if that helps...

<details>
<summary>journalctl -f output text</summary>

May 09 14:24:29 linuxnb systemd[2027]: Started dbus-:1.2-org.gnome.Boxes.SearchProvider@1.service.
May 09 14:24:29 linuxnb systemd[2027]: Started dbus-:1.2-org.gnome.Calculator.SearchProvider@1.service.
May 09 14:24:29 linuxnb systemd[2027]: Started dbus-:1.2-org.gnome.Characters.BackgroundService@1.service.
May 09 14:24:29 linuxnb systemd[2027]: Started dbus-:1.2-org.gnome.Contacts.SearchProvider@1.service.
May 09 14:24:29 linuxnb systemd[2027]: Started dbus-:1.2-org.gnome.ControlCenter.SearchProvider@1.service.
May 09 14:24:29 linuxnb systemd[2027]: Started dbus-:1.2-org.gnome.Photos@1.service.
May 09 14:24:29 linuxnb systemd[2027]: Started dbus-:1.2-org.gnome.clocks@1.service.
May 09 14:24:29 linuxnb nautilus[9269]: Connecting to org.freedesktop.Tracker3.Miner.Files
May 09 14:24:29 linuxnb systemd[2027]: Started dbus-:1.2-com.intel.dleyna\x2drenderer@1.service.
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: dLeyna core version 0.6.0
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: dleyna-renderer-service version 0.6.0
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Type[0] Level[0x13] Mask[0x4C] Flags[0x4F]
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Load file [/home/MYNAME/.config/dleyna-renderer-service.conf]
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: [General settings]
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Never Quit: F
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Connector Name: dbus
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Port: 0
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Push host port: 0
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: [Logging settings]
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Log Type : 0
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Log Level: 0x13
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: [Network filtering settings]
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Enabled : F
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Entries: (null)
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Calling GetRenderers method
May 09 14:24:29 linuxnb systemd[2027]: dbus-:1.2-org.gnome.Photos@1.service: Deactivated successfully.
May 09 14:24:29 linuxnb dleyna-renderer-service[9889]: Client :1.198 lost
May 09 14:24:29 linuxnb systemd[2027]: Started dbus-:1.2-org.gnome.Photos@2.service.
May 09 14:24:29 linuxnb gnome-software[2520]: Error marking directory as changed: Permission denied
May 09 14:24:29 linuxnb systemd[2027]: Started dbus-:1.2-com.intel.dleyna\x2drenderer@2.service.
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: dLeyna core version 0.6.0
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: dleyna-renderer-service version 0.6.0
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: Type[0] Level[0x13] Mask[0x4C] Flags[0x4F]
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: Load file [/home/MYNAME/.config/dleyna-renderer-service.conf]
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: [General settings]
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: Never Quit: F
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: Connector Name: dbus
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: Port: 0
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: Push host port: 0
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: [Logging settings]
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: Log Type : 0
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: Log Level: 0x13
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: [Network filtering settings]
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: Enabled : F
May 09 14:24:29 linuxnb dleyna-renderer-service[9918]: Entries: (null)
May 09 14:24:29 linuxnb systemd[2027]: dbus-:1.2-org.gnome.Photos@2.service: Deactivated successfully.
May 09 14:24:30 linuxnb systemd[2027]: Started Application launched by gnome-shell.
May 09 14:24:30 linuxnb systemd[2027]: Started Application launched by gnome-shell.
May 09 14:24:30 linuxnb systemd[2027]: app-glib-io.github.seadve.Kooha-9923.scope: Deactivated successfully.
May 09 14:24:30 linuxnb systemd[2027]: Started app-flatpak-io.github.seadve.Kooha-9923.scope.
May 09 14:24:30 linuxnb systemd[2027]: app-gnome-io.github.seadve.Kooha-9923.scope: Deactivated successfully.
May 09 14:24:30 linuxnb dleyna-renderer-service[9889]: dLeyna: Exit
May 09 14:24:30 linuxnb systemd[2027]: dbus-:1.2-com.intel.dleyna\x2drenderer@1.service: Deactivated successfully.
May 09 14:24:30 linuxnb systemd[2027]: Started dbus-:1.2-org.gnome.Shell.Screencast@1.service.
May 09 14:24:32 linuxnb systemd[2027]: dbus-:1.2-org.gnome.Shell.Screencast@1.service: Deactivated successfully.
May 09 14:24:39 linuxnb systemd[2027]: dbus-:1.2-org.gnome.clocks@1.service: Deactivated successfully.
May 09 14:24:39 linuxnb systemd[2027]: dbus-:1.2-org.gnome.Boxes.SearchProvider@1.service: Deactivated successfully.
May 09 14:24:39 linuxnb systemd[2027]: dbus-:1.2-org.gnome.Contacts.SearchProvider@1.service: Deactivated successfully.
May 09 14:24:46 linuxnb systemd[2027]: Started dbus-:1.2-org.gnome.Shell.Screencast@2.service.
May 09 14:24:46 linuxnb pipewire[2309]: params Spa:Enum:ParamId:EnumFormat: 0:0 Invalid argument (input format (no more input formats))
May 09 14:24:46 linuxnb pipewire[2309]: Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Id 2        (Spa:Enum:MediaType:video)
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Choice: type Spa:Enum:Choice:None, flags 00000000 20 4
May 09 14:24:46 linuxnb pipewire[2309]:       Id 2        (Spa:Enum:VideoFormat:I420)
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 09 14:24:46 linuxnb pipewire[2309]:       Rectangle 16x16
May 09 14:24:46 linuxnb pipewire[2309]:       Rectangle 16x16
May 09 14:24:46 linuxnb pipewire[2309]:       Rectangle 16383x16383
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 09 14:24:46 linuxnb pipewire[2309]:       Fraction 0/1
May 09 14:24:46 linuxnb pipewire[2309]:       Fraction 0/1
May 09 14:24:46 linuxnb pipewire[2309]:       Fraction 2147483647/1
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Choice: type Spa:Enum:Choice:None, flags 00000000 24 8
May 09 14:24:46 linuxnb pipewire[2309]:       Fraction 30/1
May 09 14:24:46 linuxnb pipewire[2309]: params Spa:Enum:ParamId:EnumFormat: 1:0 Invalid argument (output format (no more input formats))
May 09 14:24:46 linuxnb pipewire[2309]: Object: size 184, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Id 2        (Spa:Enum:MediaType:video)
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Id 8        (Spa:Enum:VideoFormat:BGRx)
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Rectangle 1920x1200
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Fraction 0/1
May 09 14:24:46 linuxnb pipewire[2309]:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 09 14:24:46 linuxnb pipewire[2309]:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 09 14:24:46 linuxnb pipewire[2309]:       Fraction 60/1
May 09 14:24:46 linuxnb pipewire[2309]:       Fraction 1/1
May 09 14:24:46 linuxnb pipewire[2309]:       Fraction 60/1
May 09 14:24:46 linuxnb pipewire[2309]: (61.0 -> 67.0) negotiating -> error (no more input formats)
May 09 14:24:46 linuxnb pipewire-media-session[2317]: can't link 61:57 -> 67:68: no more input formats
May 09 14:24:46 linuxnb pipewire-media-session[2317]: error id:12 seq:1215 res:-22 (Invalid argument): no more input formats
May 09 14:24:48 linuxnb pipewire-pulse[2310]: pulse-server 0x5555df5d2df0: [Kooha] UNDERFLOW channel:0 offset:20140 underrun:1366
May 09 14:24:49 linuxnb systemd[2027]: Starting Tracker metadata extractor...
May 09 14:24:49 linuxnb systemd[2027]: dbus-:1.2-org.gnome.Calculator.SearchProvider@1.service: Deactivated successfully.
May 09 14:24:49 linuxnb systemd[2027]: Started Tracker metadata extractor.
May 09 14:24:59 linuxnb systemd[2027]: dbus-:1.2-org.gnome.Characters.BackgroundService@1.service: Deactivated successfully.
May 09 14:24:59 linuxnb systemd[2027]: tracker-extract-3.service: Deactivated successfully.
May 09 14:25:10 linuxnb systemd[2027]: app-flatpak-io.github.seadve.Kooha-9923.scope: Deactivated successfully.
May 09 14:25:10 linuxnb systemd[2027]: app-flatpak-io.github.seadve.Kooha-9923.scope: Consumed 1.400s CPU time.
May 09 14:25:29 linuxnb systemd[2027]: dbus-:1.2-org.gnome.ControlCenter.SearchProvider@1.service: Deactivated successfully.
</details>

**Comment by SeaDve** [comment]
Thanks, the logs are helpful, but never seen this before. I'll investigate

**Comment by Leleat** [comment]
PS. I started Kooha via the GUI.

**Comment by SeaDve** [comment]
Does it also crash with both audio turned off?

**Comment by Leleat** [comment]
I didn't try to record in/output audio. I just tried the default settings (which is fullscreen with mouse).

**Comment by SeaDve** [comment]
Btw I'm also on Fedora 34, but cannot reproduce the issue. Although, I have a feeling that this might be a pipewire issue. Are we on the same version; mine's `0.3.27`. It can be get through `pipewire --version`

**Comment by Leleat** [comment]
Output:
```
pipewire
Compiled with libpipewire 0.3.26
Linked with libpipewire 0.3.26

Saw that there are new updates for Fedora now. I'll do an update and report back, if I still got the problem.

**Comment by Leleat** [comment]
After an update to `0.3.27` and a reboot, nothing changed. This time however I didn't force quit Kooha and it was able to 'recover', i. e. I could click the buttons again etc. and there was an empty video file in my video folder... `journalctl -f` gave the following output in that case (last bit is new to me but is the same as OP I think)

```
May 09 15:20:36 linuxnb systemd[1976]: Started Application launched by gnome-shell.
May 09 15:20:36 linuxnb systemd[1976]: Started Application launched by gnome-shell.
May 09 15:20:36 linuxnb systemd[1976]: Starting Mark boot as successful...
May 09 15:20:36 linuxnb systemd[1976]: app-glib-io.github.seadve.Kooha-3514.scope: Deactivated successfully.
May 09 15:20:36 linuxnb systemd[1976]: Started app-flatpak-io.github.seadve.Kooha-3514.scope.
May 09 15:20:36 linuxnb systemd[1976]: app-gnome-io.github.seadve.Kooha-3514.scope: Deactivated successfully.
May 09 15:20:36 linuxnb systemd[1976]: grub-boot-success.service: Deactivated successfully.
May 09 15:20:36 linuxnb systemd[1976]: Finished Mark boot as successful.
May 09 15:20:36 linuxnb systemd[1976]: Started dbus-:1.2-org.gnome.Shell.Screencast@3.service.
May 09 15:20:37 linuxnb systemd[1976]: dbus-:1.2-org.gnome.Characters.BackgroundService@0.service: Deactivated successfully.
May 09 15:20:38 linuxnb systemd[1976]: dbus-:1.2-org.gnome.Shell.Screencast@3.service: Deactivated successfully.
May 09 15:20:41 linuxnb systemd[1976]: Started dbus-:1.2-org.gnome.Shell.Screencast@4.service.
May 09 15:20:41 linuxnb pipewire[2258]: params Spa:Enum:ParamId:EnumFormat: 0:0 Invalid argument (input format (no more input formats))
May 09 15:20:41 linuxnb pipewire[2258]: Object: size 248, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Id 2        (Spa:Enum:MediaType:video)
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Choice: type Spa:Enum:Choice:None, flags 00000000 20 4
May 09 15:20:41 linuxnb pipewire[2258]:       Id 2        (Spa:Enum:VideoFormat:I420)
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 09 15:20:41 linuxnb pipewire[2258]:       Rectangle 16x16
May 09 15:20:41 linuxnb pipewire[2258]:       Rectangle 16x16
May 09 15:20:41 linuxnb pipewire[2258]:       Rectangle 16383x16383
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 09 15:20:41 linuxnb pipewire[2258]:       Fraction 0/1
May 09 15:20:41 linuxnb pipewire[2258]:       Fraction 0/1
May 09 15:20:41 linuxnb pipewire[2258]:       Fraction 2147483647/1
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Choice: type Spa:Enum:Choice:None, flags 00000000 24 8
May 09 15:20:41 linuxnb pipewire[2258]:       Fraction 30/1
May 09 15:20:41 linuxnb pipewire[2258]: params Spa:Enum:ParamId:EnumFormat: 1:0 Invalid argument (output format (no more input formats))
May 09 15:20:41 linuxnb pipewire[2258]: Object: size 184, type Spa:Pod:Object:Param:Format (262147), id Spa:Enum:ParamId:EnumFormat (3)
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:mediaType (1), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Id 2        (Spa:Enum:MediaType:video)
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:mediaSubtype (2), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Id 1        (Spa:Enum:MediaSubtype:raw)
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:Video:format (131073), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Id 8        (Spa:Enum:VideoFormat:BGRx)
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:Video:size (131075), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Rectangle 1920x1200
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:Video:framerate (131076), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Fraction 0/1
May 09 15:20:41 linuxnb pipewire[2258]:   Prop: key Spa:Pod:Object:Param:Format:Video:maxFramerate (131077), flags 00000000
May 09 15:20:41 linuxnb pipewire[2258]:     Choice: type Spa:Enum:Choice:Range, flags 00000000 40 8
May 09 15:20:41 linuxnb pipewire[2258]:       Fraction 60/1
May 09 15:20:41 linuxnb pipewire[2258]:       Fraction 1/1
May 09 15:20:41 linuxnb pipewire[2258]:       Fraction 60/1
May 09 15:20:41 linuxnb pipewire[2258]: (70.0 -> 60.0) negotiating -> error (no more input formats)
May 09 15:20:41 linuxnb pipewire-media-session[2267]: can't link 70:68 -> 60:61: no more input formats
May 09 15:20:41 linuxnb pipewire-media-session[2267]: error id:15 seq:853 res:-22 (Invalid argument): no more input formats
May 09 15:20:42 linuxnb pipewire-pulse[2259]: pulse-server 0x55bbb741aa50: [Kooha] UNDERFLOW channel:0 offset:20140 underrun:1366
May 09 15:20:44 linuxnb systemd[1976]: Starting Tracker metadata extractor...
May 09 15:20:44 linuxnb systemd[1976]: Started Tracker metadata extractor.
May 09 15:20:54 linuxnb systemd[1976]: tracker-extract-3.service: Deactivated successfully.
```
That is the new part:
```
May 09 15:21:06 linuxnb io.github.seadve.Kooha.desktop[3527]: Traceback (most recent call last):
May 09 15:21:06 linuxnb io.github.seadve.Kooha.desktop[3527]:   File "/app/share/kooha/kooha/window.py", line 71, in on_start_record_button_clicked
May 09 15:21:06 linuxnb io.github.seadve.Kooha.desktop[3527]:     self.delay_timer.start(delay)
May 09 15:21:06 linuxnb io.github.seadve.Kooha.desktop[3527]:   File "/app/share/kooha/kooha/timers.py", line 63, in start
May 09 15:21:06 linuxnb io.github.seadve.Kooha.desktop[3527]:     self.function()
May 09 15:21:06 linuxnb io.github.seadve.Kooha.desktop[3527]:   File "/app/share/kooha/kooha/window.py", line 101, in start_recording
May 09 15:21:06 linuxnb io.github.seadve.Kooha.desktop[3527]:     self.video_recorder.start(self.directory, framerate, show_pointer)
May 09 15:21:06 linuxnb io.github.seadve.Kooha.desktop[3527]:   File "/app/share/kooha/kooha/recorders.py", line 143, in start
May 09 15:21:06 linuxnb io.github.seadve.Kooha.desktop[3527]:     self.gnome_screencast.call_sync(
May 09 15:21:06 linuxnb io.github.seadve.Kooha.desktop[3527]: gi.repository.GLib.Error: g-io-error-quark: Timeout was reached (24)
```

**Comment by SeaDve** [comment]
I'll push a fix soon, let me know if it got fixed, thanks

**Comment by Leleat** [comment]
> I'll push a fix soon, let me know if it got fixed, thanks

Sure, tell me once you've pushed it. I'll test it then.

**Comment by SeaDve** [comment]
Ive pushed it on the main branch, together with gtk4, hopefully it got fixed

**Comment by SeaDve** [comment]
Edit: Fix now released on flathub! :D

**Comment by molitona** [comment]
The same problem reoccurred on Arch !

**Comment by Leleat** [comment]
> Edit: Fix now released on flathub! :D

Thanks, 1.2.0 does work for me as well.

**Comment by molitona** [comment]
It doesn't work on Arch.

-------- Original Message --------

**Comment by SeaDve** [comment]
> It doesn't work on Arch.

Feel free to open another issue, this issue is already containing 2 different issues

**Comment by andypillip** [comment]
I just installed Kooha¹ and it seems I'm running into the same issue on Gnome 40 with Kooha 1.2.0. Just that lines are different in the log output:

```
Traceback (most recent call last):
  File "/app/share/kooha/kooha/window.py", line 64, in on_start_record_button_clicked
    self.delay_timer.start(delay)
  File "/app/share/kooha/kooha/timers.py", line 63, in start
    self.function()
  File "/app/share/kooha/kooha/window.py", line 93, in start_recording
    self.video_recorder.start(self.directory, muxer, framerate, show_pointer)
  File "/app/share/kooha/kooha/recorders.py", line 146, in start
    self.gnome_screencast.call_sync(
gi.repository.GLib.Error: g-io-error-quark: Timeout was reached (24)
```
It seems to be exactly the same, should we reopen the issue? I'm happy to investigate more…
--- 
1) So great that there's finally a screen recorder for Wayland! Nice job!

**Comment by SeaDve** [comment]
Hi, thanks : D

It would be great to have distro informations, and i think its better to open a new issue,

**Comment by andypillip** [comment]
I ran some more upgrades and rebooted, and now it works perfectly. Thanks!

**Comment by SeaDve** [comment]
no problem :D
