### ISSUE TITLE
Please consider applying for Gnome Circle

### ISSUE THREAD

**Issue by kdwk** [SeaDve/Kooha#55]
I think this nice little utility deserves some more exposure and recognition :-)

 > Developers who are using the GNOME platform can apply to have their projects included in GNOME Circle. When their project is approved, they qualify for benefits including:
> 
>     Promotion and advertising
>     Contributors qualify for GNOME Foundation membership ( see benefits )
>     Optional inclusion in the Circle Gitlab group

GNOME Circle champions the great software that is available for the GNOME platform. It showcases the best apps available in the Gnome ecosystem.

**Comment by SeaDve** [comment]
Already did a month ago :D

**Comment by kdwk** [comment]
Excellent!

**Comment by SeaDve** [comment]
It just got accepted now =D
