### ISSUE TITLE
container/codec issue

### ISSUE THREAD

**Issue by corebots** [SeaDve/Kooha#58]
Hi and thanks for the handy app! I was wondering if you could do something regarding this - when I upload a screencap using Kooha to Slack, it won't be detected as a video, won't get a thumbnail and can't be played inline. However with the default GNOME screen recorder, which also uses a .webm, it all works as expected. See screenshot. 
![image](https://user-images.githubusercontent.com/12252430/118278866-c10a4000-b4ca-11eb-874c-64d0e5fc56fb.png)

**Comment by SeaDve** [comment]
It must be the multiplexer, I'll push a fix soon

**Comment by SeaDve** [comment]
fix pushed on main branch, you can test it here right away, let me know if the issue is fix, so I can commit it to flathub, thanks!

**Comment by corebots** [comment]
Hi and sorry I didn't respond earlier but thank you for the quick fix! Preview thumbnails now work as expected in Slack.
