### ISSUE TITLE
Error when recording Audio from either speaker or microphone

### ISSUE THREAD

**Issue by hheinzer** [SeaDve/Kooha#61]
I am getting an error that I do not know how to resolve when I try to record audio from either speaker or microphone. If I only record video, everything works fine. I am on Arch Linux and installed the package from the AUR (https://aur.archlinux.org/packages/kooha/). There is no mention of any issue on there, so I think this must be a problem with a missing package that I do not have installed for some reason. The error message is as follows:

```
Default sink: bluez_output.94_DB_56_BA_6C_F8.a2dp-sink.monitor 
Default source: alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source
audio_gst Error: gst-resource-error-quark: Could not open file "/home/hhh/.cache/tmp/tmpaudio.ogg" for writing. (6) ../gstreamer/plugins/elements/gstfilesink.c(471): gst_file_sink_open_file (): /GstPipeline:pipeline0/GstFileSink:filesink0:
system error: Bad file descriptor
audio_gst Error: gst-core-error-quark: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure. (4) ../gstreamer/libs/gst/base/gstbasesink.c(5865): gst_base_sink_change_state (): /GstPipeline:pipeline0/GstFileSink:filesink0:
Failed to start
Traceback (most recent call last):
  File "/usr/share/kooha/kooha/window.py", line 127, in on_stop_record_button_clicked
    self.video_recorder.stop()
  File "/usr/share/kooha/kooha/recorders.py", line 182, in stop
    self.gnome_screencast.call_sync(
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying (4)
Error: gst-resource-error-quark: Resource not found. (3) ../gstreamer/plugins/elements/gstfilesrc.c(536): gst_file_src_start (): /GstPipeline:pipeline1/GstFileSrc:filesrc1:
No such file "/home/hhh/.cache/tmp/tmpaudio.ogg"
```

I am using pipewire as a pulseaudio replacement, if that is of any help.

**Comment by SeaDve** [comment]
I seems to be an exclusive error with aur. If it is okay, you can test first the flatpak version, and report it here, if it is also reproducible.

**Comment by hheinzer** [comment]
Ok, the location of the `tmp` folder was a very good idea. Creating a `tmp` folder in `.cache` fixed the issue. I did not try the flatpak version, but I suspect that this will also work then. Is it maybe possible to point kooha directly to `/tmp` during the build process?

**Comment by SeaDve** [comment]
It is suppose to point directly to `/tmp` not  `~/.cache/tmp` 

Maybe I could fix it by checking if that dir exist, and creating if it doesn't

**Comment by hheinzer** [comment]
> Maybe I could fix it by checking if that dir exist, and creating if it doesn't

This seems like a good idea because Kooha expects that there a `tmp` dir in `XDG_CACHE_HOME`, which might not necessarily be the case (`f"{directory}/tmp/tmp{media_type}.{extension}")`. 

> If you mean root's tmp dir ,I'm afraid, not.

I agree that it would not really be a good idea to put it in roots `tmp` directory.

**Comment by SeaDve** [comment]
or maybe just entirely remove the second tmp/ folder? since it is already in the tmp folder?

**Comment by hheinzer** [comment]
also a sensible option, might make things less complicated overall :)

**Comment by SeaDve** [comment]
Ill push a fix tomorrow :D

**Comment by hheinzer** [comment]
Wonderful! Thank You for the quick reply and fix :smile:

**Comment by SeaDve** [comment]
Hi, just push a fixed, you could test it with the same conditions as when you first reproduced the bug, using either [this package](https://github.com/SeaDve/Kooha/suites/2807238283/artifacts/62442663) or building from source

**Comment by hheinzer** [comment]
Just tested the updated AUR package and the issue is fixed. Thank you!
