### ISSUE TITLE
[BUG] Selection doesn't select properly

### ISSUE THREAD

**Issue by dodalovic** [SeaDve/Kooha#62]
Hi, I have two monitors. On my external monitor, when I select a larger portion of it, only a small sub-portion of that gets recorded. 

PopOS Linux `20.10`, Kooha `1.2.1`

`4K` External monitor, Dell XPS 9700 4K laptop.

**Comment by SeaDve** [comment]
duplicate of https://github.com/SeaDve/Kooha/issues/18?

**Comment by dodalovic** [comment]
Yes, closing this one
