### ISSUE TITLE
Misaligned buttons and inconsistent theme

### ISSUE THREAD

**Issue by sainAk** [SeaDve/Kooha#63]
![image](https://user-images.githubusercontent.com/46787056/119354088-44911180-bcc1-11eb-975a-d2d467fa5430.png)

Since v1.2.0 the app is not following my current theme(adwaita-dark)
also the buttons are misaligned.

**Comment by SeaDve** [comment]
In gtk4, stackswitcher is no more derived from gtkbox, so I had to compensate using css to adjust it to that size making the size hard coded.

You can set the buttons as GNOME's default, but I'll find a way to fix it

**Comment by sainAk** [comment]
It seems i can force it to use dark variant of HighContrast by setting 
`gtk-application-prefer-dark-theme=1` in `~/.config/gtk-4.0/settings.ini`
![image](https://user-images.githubusercontent.com/46787056/119361762-a3f31f80-bcc9-11eb-8567-b305fc7814ce.png)

after this I also noted that launching it with inspector the theme canges to adwaita-dark automatically but the theme is still not persistent.

**Comment by SeaDve** [comment]
You can override it to persist by appending GTK_THEME=Adwaita-dark to launcher. Btw do you think is this enough?
![image](https://user-images.githubusercontent.com/64297935/119423989-25cd6200-bd37-11eb-9632-da37ef2b06f8.png)
It doesn't look as good as the GTK3 one but looks better for now, I'll find a better fix

**Comment by sainAk** [comment]
> You can override it to persist by appending GTK_THEME=Adwaita-dark to launcher. 
Okay.

> Btw do you think is this enough?
> ![image](https://user-images.githubusercontent.com/64297935/119423989-25cd6200-bd37-11eb-9632-da37ef2b06f8.png)
> It doesn't look as good as the GTK3 one but looks better for now, I'll find a better fix

yep I did the same, it looks better

**Comment by SeaDve** [comment]
merged to main
