### ISSUE TITLE
Cancel the conversion

### ISSUE THREAD

**Issue by andypillip** [SeaDve/Kooha#66]
I'm recording screencasts with audio, and sometimes I realise I made a mistake and would like to start over. If I recorded several minutes, I need to wait for the conversion to finish, though.

It would be nice to be able to abort the conversion and abandon the video.

**Comment by SeaDve** [comment]
Should be fixed in 2.0.0 :D 

Because the video will no longer need to process

**Comment by SeaDve** [comment]
the fix is merged to main :D thanks
