### ISSUE TITLE
Can't access actual home folder so it saves file on a 'hidden' directory

### ISSUE THREAD

**Issue by uriva** [SeaDve/Kooha#67]
installed this on ubuntu 21.04, the record button has no effect (and neither does ctrl r). that is - it's clickable but doesn't seem to  do anything.

**Comment by SeaDve** [comment]
hmm, what version, and where is it installed?

**Comment by uriva** [comment]
version 1.2.1

**Comment by uriva** [comment]
installed by downloading a file from here: https://flathub.org/apps/details/io.github.seadve.Kooha

**Comment by uriva** [comment]
managed to get a stack trace:
```

Traceback (most recent call last):
  File "/app/share/kooha/kooha/window.py", line 56, in on_start_record_button_clicked
    self.directory, video_directory, frmt = self.get_saving_location()
  File "/app/share/kooha/kooha/window.py", line 107, in get_saving_location
    if not os.path.exists(video_directory):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```

**Comment by uriva** [comment]
apparently it relies on me having a `~/videos` dir

**Comment by SeaDve** [comment]
that's weird, it should also be reproducible when clicking, not only on shortcut

**Comment by uriva** [comment]
it is...

**Comment by SeaDve** [comment]
On both clicking and the shortcut?

**Comment by uriva** [comment]
right

**Comment by SeaDve** [comment]
A temporary fix is to manually set the saving location in the hamburger menu

**Comment by uriva** [comment]
that doesn't work either.
when trying to set a different directory i get a dialog:
```
Save location not set
Please choose an accessible location and retry
```

**Comment by SeaDve** [comment]
The location must be within the home directory, but not exactly the home directory

**Comment by uriva** [comment]
i managed to create a dir and record to it, but although kooha claims the path is in my home dir, i can't get to it outside kooha. seems like some kind of sandboxing.

**Comment by SeaDve** [comment]
with your patches?

**Comment by uriva** [comment]
not sure i understand why it works at all then (for other users)

**Comment by SeaDve** [comment]
The default is to save to xdg-videos, if it doesn't exist then home. Probably, there is very few people who don't have xdg-videos

**Comment by SeaDve** [comment]
Couldn't think of an elegant solution without having to expose the entire home folder

**Comment by SeaDve** [comment]
@uriva I've rewritten the logic to this, can I ask you a question? Do you have a ~/Videos folder when you received this error?

**Comment by uriva** [comment]
I got it to work with building from source, I can uninstall and try again, did you release the new version?
I also restored my Videos directory. When I opened this issue I didn't have it.

**Comment by SeaDve** [comment]
Not yet, there's things that needs polish.

**Comment by SeaDve** [comment]
merged to main branch

**Comment by mlncn** [comment]
Does this mean that my apparently unsaved video may be saved somewhere?  Where is this 'hidden' directory?  It should probably warn before recording with the save location not yet set!

**Comment by SeaDve** [comment]
If you're on flatpak, kooha won't know if you really saved it in the 'hidden' directory.

This happens when kooha thought that it is accessing the home folder, but actually an artificial home folder created by the environment.

In version 1.2.1 or older, when you have no xdg-videos folder, this bug will occur. But luckily, in latest commits, this will never happen, it will error if it does
