### ISSUE TITLE
.MKV is a weird default

### ISSUE THREAD

**Issue by jannuary** [SeaDve/Kooha#7]
In my experience, .mkv is less compatible with things like IM apps, social networks, etc. compared to .webm, so it's a little bit weird to have that as a default.

**Comment by SeaDve** [comment]
Thanks for the suggestion!
You're right, it's just MKV since when it was using FFmpeg as a backend, WebM is such a mess to deal with.
I guess I'll push webm as default in v1.0.2

**Comment by SeaDve** [comment]
https://github.com/SeaDve/Kooha/commit/86a5015430e10367d62707a949a3b136c2d3bcba
