### ISSUE TITLE
Incorrect layout of interface elements

### ISSUE THREAD

**Issue by gavr123456789** [SeaDve/Kooha#70]
![image](https://user-images.githubusercontent.com/30507409/121011319-2508e700-c79f-11eb-8749-8c225c145693.png)
Linux: Arch  
Installed from: Flathub

**Comment by SeaDve** [comment]
It's not incorrect, although unideal/looks ugly with non-default title bar button placements. The only thing I can possibly do is to expand the switcher (#63).

Also there is something that changed in gtk4 wherein it centers the child of headerbar by default, unlike in gtk3.

**Comment by SeaDve** [comment]
![image](https://user-images.githubusercontent.com/64297935/121028615-9023df00-c7da-11eb-8594-1604f1e0e8f4.png)

here's some experiment, it doesn't look as good as default, but definitely better?

**Comment by SeaDve** [comment]
I'll close this, and continue with #63

**Comment by gavr123456789** [comment]
Yea, looks almost same, except width.  
I think it's enough to add an alignment group here... may be.

**Comment by SeaDve** [comment]
I think alignment group no longer exist in gtk4, not sure

**Comment by SeaDve** [comment]
Found a weird workaround: It is to set default width to something small

**Comment by gavr123456789** [comment]
Is there a GTK 4 bug here by chance? I do not think that the location of the window control buttons should somehow affect the layout.

**Comment by SeaDve** [comment]
> Is there a GTK 4 bug here by chance? I do not think that the location of the window control buttons should somehow affect the layout.

I don't think so, the hamburger menu is part of the headerbar so setting the titlebar buttons to show to the left will move the menu
