### ISSUE TITLE
Follow system's default theme

### ISSUE THREAD

**Issue by stpnwf** [SeaDve/Kooha#77]
Would it be possible to allow Kooha's main window to use the system's default theme? Unsure if it is because I am using the Flatpak version, but Kooha on my machine is white and I would like for it to follow my theme's style.

**Comment by SeaDve** [comment]
this is an issue for libadwaita, since it currently doesn't support it, but you can force it temporarily in gtk inspector to use system theme

**Comment by stpnwf** [comment]
Thanks, I will look into that

**Comment by SeaDve** [comment]
no prob, i think this will be fixed before gnome 41 and libadwaita's release

**Comment by SeaDve** [comment]
Closing this as unactionable from Kooha's side.
