### ISSUE TITLE
UI too wide

### ISSUE THREAD

**Issue by corebots** [SeaDve/Kooha#82]
Hi, please close if known or duplicate, but I couldn't find this mentioned between the issues here. since one of the updates, must've been like a month ago, Kooha interface got wider. I thought this is temporary so didn't report, but now an update later it's still the same. Would be nice to have the smaller compact window again :) Besides that, it seems to work fine, so thanks for the work!
![image](https://user-images.githubusercontent.com/12252430/123935790-d6f99480-d994-11eb-8a9c-89b841eb7d40.png)

**Comment by SeaDve** [comment]
Thanks for reporting!

Although, it is related to #63 and #70

The fix is already pushed to main branch, but isn't released yet on flathub.

So gonna close this
