### ISSUE TITLE
Columns (:) in filenames

### ISSUE THREAD

**Issue by spxak1** [SeaDve/Kooha#84]
Hello,

not all filesystems support columns in filenames and as such copying a Kooha recording to exFAT of via SAMBA to another ext4 filesystem fails.

Please change columns to simple dots in filenames.

Thank you for this excellent tool.

**Comment by SeaDve** [comment]
What do you think of using `∶` ratio symbol?

**Comment by SeaDve** [comment]
I'm worried that dots may cause issue with the path, so possibly, ratio or underscore are the choices

**Comment by verbalius** [comment]
also when you want to convert in ffmpeg it interprets it wrong.
![image](https://user-images.githubusercontent.com/26470717/133433643-5d821b5e-69be-439d-81ee-14f9b9b81cf3.png)

**Comment by TheFlagCourier** [comment]
> What do you think of using `∶` ratio symbol?

Not so sure that's advisable. Ideally, the only symbols should be underscores `_`, periods `.`, and hyphens `-`.

Something like: `Kooha-2021-09-17-10_54_23.mkv` would make much more sense for file-system compatibility.

Alternatively, just using the system timestamp should be sufficient.
