### ISSUE TITLE
"The name org.freedesktop.portal.Desktop was not provided by any .service file" error whit latest git 

### ISSUE THREAD

**Issue by dasnoopy** [SeaDve/Kooha#85]
Hi, I successfully compiled and installed Kooha with  latest git version ( v1.2.1.r249.gd15fb52-1) on my Archlinux  machine (Xorg 1.20.11 / gtk4 v4.2.1 / libadwaita-git latest version)  using a  PKGBUILD-git file  creaated from scratch*

The app start normally but when I ty to record something , obtain this error :  (both in  Xorg and Wayland)

> $kooha
ERROR:root:g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files (2)
Traceback (most recent call last):
  File "/usr/share/kooha/kooha/backend/screencast_portal.py", line 125, in _screencast_call
    method(signature, *args, options)
  File "/usr/lib/python3.9/site-packages/gi/overrides/Gio.py", line 349, in __call__
    result = self.dbus_proxy.call_sync(self.method_name, arg_variant,
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files (2)
INFO:kooha.backend.recorder:is_show_pointer: True
INFO:kooha.backend.recorder:is_selection_mode: True

*Just for the record version  kooha release 1.2.1  compiled  from [AUR](https://aur.archlinux.org/packages/kooha)  , worked fine

Any suggestion about the error?

thanks in advance
Andrea

**Comment by SeaDve** [comment]
What distro or wm are you in?

**Comment by dasnoopy** [comment]
thanks  for the quick reply  .. I'm on Gnome 40.2  

As per your suggestion I've added `xdg-desktop-portal`  and  `xdg-dekstop-portak-gtk`  as building dependencies and everything works fine..

from my side issue can be marked as solved :slightly_smiling_face:

Thanks again
Andrea

**Comment by SeaDve** [comment]
No problem :D

I guess we can close this

**Comment by SeaDve** [comment]
Btw, I think they are more of runtime dependencies because they aren't needed at build time.

**Comment by major-mayer** [comment]
Thank you for mentioning that you need libadwaita-git on Arch Linux.
I was trying to build Kooha on Manjaro/ Arch but it always failed with a linker error, related to libadwaita.
I guess the packaged version is just too old for this project.

@SeaDve Maybe you could add this to the requirements somewhere? It could prevent some bug reports in the future
