### ISSUE TITLE
Add support to Weblate

### ISSUE THREAD

**Issue by LeandroStanger** [SeaDve/Kooha#9]
https://weblate.org

**Comment by rffontenelle** [comment]
Or [Damned Lies](l10n.gnome.org/), since this is a [GNOME Circle](https://circle.gnome.org/) app.

**Comment by SeaDve** [comment]
It is not or yet a GNOME Circle app as of now. But would be considering both.

**Comment by rffontenelle** [comment]
@SeaDve My bad, I was just now in that website and I was sure Kooha was listed, but looks like that's not true.

**Comment by SeaDve** [comment]
Not sure how to support either damned lies or weblate. But I'll push soon the pot files.

**Comment by SeaDve** [comment]
https://github.com/SeaDve/Kooha/commit/05057ad6b37501657f1d9548d3d39ca6835fe83d 
Does this commit closes this issue?

**Comment by SeaDve** [comment]
https://hosted.weblate.org/projects/kooha/pot-file/

**Comment by TheOPtimal** [comment]
I recommend using Damned Lies, let's make this a GNOME Circle project.
