### ISSUE TITLE
Opaque (black) area selector on sway

### ISSUE THREAD

**Issue by SeaDve** [SeaDve/Kooha#93]
Some related:
- [ ] There should be fade (not window) animation when closing the selector window
- [ ] Don't show on taskbar or overview
- [ ] Don't hide status bar

#42

**Comment by SeaDve** [comment]
Ill check again of slurp, if it works now on gnome

**Comment by SeaDve** [comment]
slop seems to support both gnome and sway. Patches are welcome

**Comment by SeaDve** [comment]
I'm thinking of writing a separate program, using xlib since slop has too many dependencies

**Comment by asjur** [comment]
I decided to check out slop. It seems a bit abandoned when looking into commit and git issue history.

Is it not viable to use slurp for wlroots based WMs like Sway? You already detect environment so if sway/wlroots get coordinates etc using slurp? If gnome, continue as you are.

**Comment by SeaDve** [comment]
Splitting the code would be kinda make the code more messy. Since, the current implementation that works on gnome is also hacky, I think it would be better to implement something similar to slop, since it seems to work well on almost all environment without splitting the code

**Comment by ProjectInfinity** [comment]
Has there been any progress on this?

**Comment by SeaDve** [comment]
I don't have much time to work on Kooha anymore as before, if anyone would like to submit a pr, it would be great

**Comment by SeaDve** [comment]
Fixed on main branch with a non-hacky area selector: 

https://github.com/SeaDve/Kooha/commit/b025b8ad5d6d36f6b261e8c175eb77518690ff11

![image](https://user-images.githubusercontent.com/64297935/192681200-91ced554-4147-440e-badf-1770901647d1.png)
