### ISSUE TITLE
Where is the GIF support?

### ISSUE THREAD

**Issue by dubst3pp4** [SeaDve/Kooha#98]
The README mentions that Kooha also supports GIF as an output file format:
> :vhs: Support for WebM, MP4, GIF, and MKV formats.

But whenever I click the video formats menu in the preferences, there is just WebM and MKV. Do I have to install something additionally?

I'm running Kooha 1.2.1 as a Flatpak app on Ubuntu 21.04.

Thanks for your great work!

**Comment by SeaDve** [comment]
It already does, but on main branch

**Comment by SeaDve** [comment]
I haven't release it yet because I'm waiting for gnome 41 runtime

**Comment by SeaDve** [comment]
I guess I can close this, thnx!

**Comment by dubst3pp4** [comment]
> I haven't release it yet because I'm waiting for gnome 41 runtime
> 
> The readme on GitHub refers to the main branch, you can refer to the readme in the flathub page for released features.

Thanks for the info! :+1:
